const questionsSEP = [
  { q: 'Jaki akt prawny reguluje kompleksowo przepisy BHP?', a: 'Podstawowym aktem prawnym regulującym przepisy BHP jest Dział X ustawy z dnia 2.02.1996 r. „Kodeks Pracy" (Dz. U. nr 24 z 1996 r.) – obowiązujący od 2 czerwca 1996 roku.' },
  { q: 'Jaki akt prawny reguluje gospodarkę energetyczną i kto ją nadzoruje?', a: 'Prawo energetyczne – ustawa z dnia 10 kwietnia 1997 r. (Dz. U. nr 54 z dnia 4.06.1997 r.). Obowiązuje od 5 grudnia 1997 r. Nadzór sprawuje Urząd Regulacji Energetyki (URE).' },
  { q: 'Kto ma prawo eksploatować urządzenia energetyczne?', a: 'Osoby sprawujące dozór nad eksploatacją urządzeń energetycznych oraz osoby eksploatujące te urządzenia w zakresie obsługi, konserwacji, remontów, montażu, kontrolno-pomiarowym, pod warunkiem posiadania dodatkowych kwalifikacji tj. świadectw kwalifikacyjnych.' },
  { q: 'Podaj efekty oddziaływania prądu przemiennego na organizm człowieka.', a: '- Ponad 25mA – początek skurczów mięśni;\n- Ponad 70mA – początek migotania komór sercowych;\n- Ponad 200mA – migotanie komór serca (skurcz mięśni sercowych – ograniczenie krążenia krwi);\n- Ponad 3A – paraliż i zatrzymanie pracy serca;\n- Ponad 5A – zwęglenie tkanek organizmu.' },
  { q: 'Podaj podstawowe obowiązujące normy w zakresie ochrony przeciwporażeniowej.', a: '- PN-IEC 60364-4-41:2000 – Instalacje elektryczne w obiektach budowlanych. Ochrona dla zapewnienia bezpieczeństwa. Ochrona przeciwporażeniowa;\n- PN-IEC 60364-4-47:2001 – Instalacje elektryczne w obiektach budowlanych. Ochrona dla zapewnienia bezpieczeństwa. Stosowanie środków ochrony zapewniających bezpieczeństwo. Postanowienia ogólne. Środki ochrony przed porażeniem prądem elektrycznym.\n- PN-IEC 60364-5-54:1999 – Instalacje elektryczne w obiektach budowlanych. Dobór i montaż wyposażenia elektrycznego. Uziemienia i przewody ochronne.\n- PN-IEC 60364-6-61:2000 – Instalacje elektryczne w obiektach budowlanych. Sprawdzanie. Sprawdzanie odbiorcze.' },
  { q: 'Jaki akt prawny określa wymagania rezystancji izolacji w instalacjach elektrycznych?', a: 'PN-IEC 60364-6-61:2000 – Instalacje elektryczne w obiektach budowlanych. Sprawdzanie. Sprawdzanie odbiorcze.' },
  { q: 'Z jakich przepisów dotyczących ochrony przeciwporażeniowej można korzystać do urządzeń wykonanych przed wejściem w życie PN-IEC 60364?', a: 'Zasady wiedzy technicznej.' },
  { q: 'Od kiedy wprowadzono obowiązek stosowania w instalacjach elektrycznych wyłączników przeciwporażeniowych oraz prowadzenie oddzielnie przewodu ochronnego i neutralnego?', a: 'Od 1 kwietnia 1995 roku. Rozporządzenie Ministra Budownictwa z dnia 14.12.1994 r. (Dz.U. nr 10 z 1995 r.).' },
  { q: 'Podaj wysokość napięcia bezpiecznego ~ UL (roboczego i dotyku) w zależności od warunków środowiskowych.', a: 'a) Dla prądu przemiennego:\n- 50V – warunki środowiskowe 1 (pomieszczenia suche);\n- 25V – warunki środowiskowe 2 (pomieszczenia mokre i gorące);\nb) Dla prądu stałego:\n- 120V – warunki środowiskowe 1 (pomieszczenia suche);\n- 60V – warunki środowiskowe 2 (pomieszczenia mokre i gorące).' },
  { q: 'Jaki prąd jest bardziej niebezpieczny?', a: 'Prąd przemienny, ponieważ powoduje trwały skurcz mięśni sercowych (migotanie komór sercowych) znacznie zmniejszenie krążenia krwi. Prąd stały nie powoduje wyżej wymienionych skutków tylko działanie cieplne i elektrolityczne.' },
  { q: 'Co to jest część czynna i części jednocześnie dostępna?', a: 'Część czynna jest to część przewodząca prąd elektryczny znajdująca się w czasie normalnej pracy pod napięciem. Części jednocześnie dostępne to części przewodzące dostępne i obce znajdujące się w zasięgu ręki. „Zasięg ręki" – obszar wokół człowieka w kształcie walca o średnicy 2,5 m, wysokości 2,5 m i 1,25 m poniżej ustawienia stóp.' },
  { q: 'Podaj wymagania dotyczące rezystancji izolacji w instalacjach elektrycznych.', a: 'Według normy PN-IEC-60364-6-61 o napięciu do 500V, R iz ≥ 0,5 MΩ; o napięciu ponad 500V – R iz ≥ 1MΩ.' },
  { q: 'Od czego zależą skutki porażenia prądem elektrycznym?', a: '- Natężenia prądu;\n- Czasu przepływu prądu;\n- Drogi przepływu prądu oraz rodzaju prądu i warunków środowiskowych.' },
  { q: 'Wymień klasy ochronności urządzenia i czym się charakteryzują.', a: '- Klasa 0 – urządzenie posiada tylko ochronę podstawową (izolację roboczą);\n- Klasa I – urządzenie posiada izolację roboczą i zacisk do ochrony dodatkowej;\n- Klasa II – urządzenie posiada izolację ochronną (podwójną lub wzmocnioną);\n- Klasa III – urządzenie na napięcie nie przekraczające napięcia bezpiecznego UL.' },
  { q: 'Co to jest napięcie dotyku?', a: 'Jest to napięcie występujące w warunkach normalnych i zakłóceniowych, między dwoma częściami jednocześnie dostępnymi nie należącymi do obwodu elektrycznego.' },
  { q: 'Co to jest napięcie rażenia?', a: 'Jest to spadek napięcia występujący wzdłuż drogi przepływu prądu przez ciało człowieka.' },
  { q: 'Podaj różnicę między napięciem dotyku i napięciem rażenia.', a: 'Napięcie dotyku jest sumą spadków napięć na ciele człowieka, obuwiu i podłożu. Napięcie rażenia jest to spadek napięcia tylko na ciele człowieka.' },
  { q: 'Co to jest napięcie krokowe?', a: 'Jest to spadek napięcia, występujący na powierzchni ziemi pomiędzy stopami człowieka spowodowany zwarciem doziemnym.' },
  { q: 'Ile wynosi rezystancja ciała człowieka (Rc)?', a: '1000 ± 50 omów.' },
  { q: 'Jaka wartość prądu rażenia jest dla człowieka bezpieczna (Jr)?', a: 'UL – napięcie bezpieczne (dla prądu stałego prąd bezpieczny jest do 60mA).' },
  { q: 'Jak zapewniamy ochronę przed porażeniem prądem elektrycznym?', a: 'Przez zastosowanie napięcia bezpiecznego lub ochrony przed dotykiem bezpośrednim lub pośrednim.' },
  { q: 'Przy jakich urządzeniach elektrycznych należy zastosować ochronę przed porażeniem?', a: 'Przy każdym, na którego obudowie może się pojawić niebezpieczne napięcie dotyku, a odbiornik nie jest zasilany z transformatora lub przetwornicy separacyjnej lub nie zastosowano w nim izolacji ochronnej.' },
  { q: 'Co zaliczamy do ochrony przed dotykiem bezpośrednim (do ochrony podstawowej)?', a: 'Izolację roboczą, osłony, obudowy, ogrodzenia, bariery, bezpieczne odstępy od urządzeń elektrycznych, instalowanie urządzeń poza „zasięgiem ręki". Obudowa winna mieć stopień ochrony co najmniej IP2X.' },
  { q: 'Jakie zadania ma ochrona podstawowa (przed dotykiem bezpośrednim)?', a: 'Nie dopuścić do bezpośredniego zetknięcia się człowieka z częściami urządzeń elektrycznych będących pod napięciem, do udzielenia się napięcia na przedmioty przewodzące, których mógłby się dotknąć człowiek oraz do przeskoku łuku elektrycznego.' },
  { q: 'Wymień środki ochrony przed dotykiem pośrednim (ochrony dodatkowej).', a: '- Samoczynne wyłączenie zasilania (uziemienie, zerowanie, wyłączniki różnicowo-prądowe);\n- Izolacja ochronna;\n- Izolowanie stanowiska;\n- Separacja;\n- Połączenia wyrównawcze.' },
  { q: 'Co to jest uziemienie ochronne?', a: 'Jest to środek ochrony dodatkowej polegający na połączeniu części przewodzących z uziomem i powodujący w warunkach zakłóceniowych samoczynne odłączenie zasilania. Może być stosowane w urządzeniach prądu stałego i przemiennego, niezależnie od ich napięcia znamionowego.' },
  { q: 'Jakie wymagania muszą być spełnione dla uziemienia ochronnego?', a: 'Uziemienie jest skuteczne, jeżeli: RA × Ja ≤ UL. RA – rezystancja uziemienia ochronnego, Ja – prąd zapewniający samoczynne wyłączenie w czasie bezpiecznym dla człowieka.' },
  { q: 'Co to jest prąd zapewniający samoczynne wyłączenie (Ja)?', a: 'Jest to prąd dostatecznie szybkiego zadziałania, którego zadaniem jest niedopuszczenie do powstania niebezpiecznego napięcia dotyku, a jeżeli takie napięcie na obudowie powstanie, wyłączy to urządzenie w czasie bezpiecznym dla człowieka. Np. przy napięciu 235V w czasie do 0,4 sekundy w pomieszczeniach normalnych, i do 0,2 sekundy w pomieszczeniach szczególnie niebezpiecznych.' },
  { q: 'Od czego zależy prąd zapewniający samoczynne wyłączenie?', a: 'Od rodzaju i wielkości zabezpieczenia: Ja = k × Jb, np. dla bezpieczników topikowych k=5 (dla wył. inst. typu „B") oraz k=10 (dla wył. inst. typu „C").' },
  { q: 'W jakich sieciach można stosować zerowanie?', a: 'W układach sieciowych TN-C, tj. w sieciach prądu przemiennego do 500V przystosowanych do zerowania, w których punkt zerowy transformatora jest bezpośrednio uziemiony, a wyprowadzony przewód neutralny możliwie licznie uziemiony.' },
  { q: 'Jakich wartości nie może przekroczyć impedancja pętli zwarcia przy zerowaniu?', a: 'Zs × Ja ≤ Uo (gdzie Uo – napięcie w stosunku do ziemi, Ja – prąd zapewniający samoczynne wyłączenie).' },
  { q: 'Kiedy zerowanie będzie skuteczne?', a: 'Jeżeli: Zs × Ja ≤ Uo lub Jz > Ja. Zs – impedancja pętli zwarcia; Jz – prąd zwarcia.' },
  { q: 'Jakim kolorem winien być oznaczony przewód neutralny (N) i ochronny (PE)?', a: 'Przewód neutralny – kolorem niebieskim. Przewód ochronny – kolorem żółto-zielonym.' },
  { q: 'Jakie wymagania muszą spełniać wyłączniki przeciwporażeniowe różnicowo-prądowe?', a: 'Powinny wyłączyć z sieci chronione urządzenia w czasie 0,4 sekundy lub 0,2 sekundy (w zależności od pomieszczeń) od czasu pojawienia się prądu różnicowego, równego prądowi wyzwalającemu wyłącznika.' },
  { q: 'Jaką czułość powinien mieć wyłącznik różnicowo-prądowy?', a: 'Zależnie od układu i pomieszczeń, np. w mieszkaniach: 30mA.' },
  { q: 'Co należy stosować do obniżenia napięcia?', a: 'Transformator bezpieczeństwa wykonany według normy PN/E-08105 lub przetwornicę bezpieczeństwa wykonaną według normy PN/E-08104.' },
  { q: 'Do ilu wolt należy obniżyć napięcie po stronie wtórnej transformatora bezpieczeństwa?', a: 'Do napięcia 50V prądu przemiennego oraz 100V dla prądu stałego dla pomieszczeń suchych; do 25V prądu przemiennego oraz 50V prądu stałego dla pomieszczeń szczególnie niebezpiecznych.' },
  { q: 'Co to jest separacja odbiornika?', a: 'Jest to oddzielenie obwodu odbiornika od obwodu zasilania przez transformator lub przetwornicę separacyjną.' },
  { q: 'Do jakich napięć sieci można stosować separację?', a: 'Do 500V prądu przemiennego i 750V prądu stałego.' },
  { q: 'Na jakie górne napięcie znamionowe może być odbiornik w obwodzie odseparowanym?', a: 'Na napięcie do 500V prądu przemiennego lub na napięcie 750V prądu stałego, prądu odbiornika nie ogranicza się.' },
  { q: 'Jakie warunki muszą być spełnione przy separacji?', a: 'W obwodzie odseparowanym może być tylko jeden odbiornik na napięcie do 500V prądu przemiennego lub na napięcie 750V prądu stałego.' },
  { q: 'Czy można stosować więcej odbiorników w obwodzie odseparowanym?', a: 'Wyjątkowo w pomieszczeniach o charakterze nieprzemysłowym dopuszcza się instalowanie większej ilości odbiorników. Części przewodzące winny być połączone za pomocą izolowanych połączeń wyrównawczych.' },
  { q: 'Podaj rezystancję transformatora separacyjnego i izolacji obwodów odseparowanych.', a: '20 MΩ między uzwojeniem pierwotnym i wtórnym. Rezystancja izolacji obwodów to co najmniej 500 kΩ.' },
  { q: 'Dla jakich urządzeń i odbiorników można stosować sieć ochronną?', a: 'Do odbiorników niezależnie od ich napięcia znamionowego, jeżeli zasilane są z osobnego transformatora z oddzielonymi uzwojeniami, osobnego zespołu prądotwórczego lub baterii/akumulatorów. Stosujemy w układach IT.' },
  { q: 'Jakie wymagania musi spełniać sieć ochronna?', a: 'Wszystkie przedmioty metalowe i części urządzeń elektrycznych muszą być metalicznie połączone z uziemioną siecią ochronną. Sieć ochronna musi być wyposażona w urządzenia do kontroli stanu izolacji.' },
  { q: 'Podać wartość rezystancji izolacji roboczej, dodatkowej i wzmocnionej odbiorników.', a: 'Co najmniej: 2 MΩ – izolacja robocza; 5 MΩ – izolacja dodatkowa; 7 MΩ – izolacja wzmocniona.' },
  { q: 'Jak są oznaczone odbiorniki, w których zastosowano izolację ochronną?', a: 'Są to odbiorniki klasy II ochronności.' },
  { q: 'Kiedy można zastosować izolowanie stanowiska?', a: 'Jeżeli odbiornik zainstalowany jest na stałe i w pomieszczeniach suchych, bez względu na napięcie znamionowe odbiornika.' },
  { q: 'Sposób uwalniania porażonego prądem przy urządzeniach do 1 kV.', a: 'Przez wyłączenie napięcia; przez odciągnięcie stosując sprzęt ochronny lub suchą tkaninę; przez odizolowanie.' },
  { q: 'Uwalnianie porażonego przy urządzeniach powyżej 1 kV.', a: 'Przez wyłączenie napięcia; przez odciągnięcie porażonego stosując sprzęt ochronny.' },
  { q: 'Co należy robić po uwolnieniu porażonego spod działania prądu elektrycznego?', a: 'Sprawdzić czy porażony oddycha. Jeżeli nie oddycha, zastosować sztuczne oddychanie; jeżeli dodatkowo brak tętna – masaż serca.' },
  { q: 'Jak dzielimy układy sieciowe?', a: 'Na układy: TT, IT, TN-C, TN-S, TN-C-S.' },
  { q: 'Kto ma prawo wystawiać polecenia pisemne?', a: 'Osoba posiadająca zaświadczenie „D" (dozoru) i upoważniona pisemnie przez prowadzącego eksploatację urządzeń energetycznych.' },
  { q: 'Co winno być uwzględnione w poleceniach pisemnych?', a: 'Miejsce, czas i rodzaj wykonywanej pracy; środki, przy pomocy których praca ma być wykonana; pracownik przygotowujący miejsce pracy i dopuszczający do pracy oraz osoba kierująca lub nadzorująca.' },
  { q: 'W ilu egzemplarzach pisze się polecenie pisemne oraz okres ich przechowywania?', a: 'W trzech egzemplarzach i przechowuje się je przez 90 dni od zakończenia prac.' },
  { q: 'Na czym polega przygotowanie miejsca pracy?', a: 'Na wyłączeniu urządzenia; sprawdzeniu braku napięcia; rozładowaniu; uziemieniu; wywieszeniu tabliczek ostrzegawczych i informacyjnych; zabezpieczeniu i oznaczeniu miejsca wykonywania prac.' },
  { q: 'Jakie prace mogą być wykonane bez polecenia?', a: 'Prace związane z ratowaniem życia i zdrowia oraz urządzeń i mienia.' },
  { q: 'Jakie prace wymagają wystawienia polecenia pisemnego?', a: 'Prace wykonywane w warunkach szczególnego zagrożenia dla zdrowia i życia ludzkiego (pod napięciem lub w pobliżu urządzeń będących pod napięciem).' },
  { q: 'Jak dzielimy sprzęt ochronny?', a: 'Na zasadniczy i dodatkowy.' },
  { q: 'Sprzęt zasadniczy do 1 kV.', a: 'Rękawice dielektryczne, narzędzia monterskie, wskaźniki napięcia, cęgi do bezpieczników, drążki izolacyjne.' },
  { q: 'Podaj okresy badań sprzętu ochronnego.', a: 'Rękawice, kalosze, półbuty i wskaźniki neonowe – co 6 miesięcy; pomosty izolacyjne co 3 lata; pozostały sprzęt co 2 lata.' },
  { q: 'Jakimi gaśnicami można gasić urządzenie elektryczne?', a: 'Gaśnicą śniegową, proszkową i halonową.' },
  { q: 'Kto i ile kary pieniężnej może nałożyć za brak uprawnień lub zły stan techniczny urządzeń?', a: 'Prezes URE na kierownika przedsiębiorstwa w wysokości do 300% jego wynagrodzenia miesięcznego i na przedsiębiorstwo do 15% przychodu za rok ubiegły.' },
  { q: 'Kogo zaliczamy do służb eksploatacyjnych?', a: 'Osoby sprawujące kierownictwo i dozór nad eksploatacją urządzeń energetycznych, osoby wykonujące usługi w zakresie konserwacji i napraw oraz osoby obsługujące urządzenia energetyczne.' },
  { q: 'Co powinny określać instrukcje o eksploatacji urządzeń energetycznych?', a: 'Ogólną charakterystykę techniczną; czynności związane z uruchomieniem, obsługą i zatrzymaniem; zasady postępowania w razie awarii, pożaru; zakresy i terminy pomiarów; zakresy i terminy przeglądów; wymagania ochrony; wymagania kwalifikacyjne.' },
  { q: 'Podaj częstotliwość pomiarów rezystancji izolacji oraz skuteczności ochrony przeciwporażeniowej.', a: 'W pomieszczeniach o wyziewach żrących, bardzo wilgotnych, gorących (>35°C) i na otwartym powietrzu – co najmniej raz w roku. W pozostałych pomieszczeniach publicznych – nie rzadziej niż co 2 lata; w pozostałych – nie rzadziej niż co 5 lat.' },
  { q: 'Jaki akt prawny reguluje wymagania kwalifikacyjne dla osób zatrudnionych przy urządzeniach energetycznych?', a: 'Rozporządzenie Ministra Gospodarki, Pracy i Polityki Społecznej z dnia 28 kwietnia 2003 r. (Dz.U. 2003 nr 89 poz. 828).' },
  { q: 'Gdzie należy instalować ograniczniki przepięć w sieciach do 1kV?', a: 'Między każdym przewodem fazowym a przewodem PEN lub PE. Na końcu linii oraz w odległości co 300 m między nimi. Rezystancja uziemienia ograniczników nie może przekraczać 10Ω.' },
  { q: 'Czy stosowanie Polskich Norm jest obowiązkowe?', a: 'Od 2003 roku stosowanie Polskich Norm jest dobrowolne.' },
  { q: 'Kiedy użytkownik (odbiorca) może żądać sprawdzenia układu pomiarowego i kto za to płaci?', a: 'Na każde żądanie odbiorcy w terminie do 14 dni. Koszty pokrywa odbiorca tylko wtedy, gdy nie stwierdzono nieprawidłowości w działaniu układu pomiarowego.' },
  { q: 'Jakie mogą być odchylenia napięcia i częstotliwości w dostawie energii elektrycznej?', a: 'Napięcie: -10% do +5% napięcia znamionowego; Częstotliwość: 50 Hz z odchyleniami -0,5 Hz do +0,2 Hz.' },
  { q: 'Kiedy dostawca może wstrzymać dostarczanie energii?', a: 'Gdy odbiorca zwleka z zapłatą co najmniej miesiąc po upływie terminu płatności, pomimo upomnienia na piśmie.' },
  { q: 'Kiedy dostawca może zainstalować przedpłatowy układ pomiarowy?', a: 'Jeżeli odbiorca co najmniej dwukrotnie w ciągu roku zwlekał z zapłatą przez okres co najmniej jednego miesiąca. Koszty ponosi dostawca.' },
  { q: 'Podaj klasyfikację stref zagrożonych wybuchem.', a: 'Z0 – mieszanina wybuchowa występuje stale; Z1 – może występować w normalnych warunkach; Z2 – niewielkie prawdopodobieństwo wystąpienia.' },
  { q: 'Podaj rodzaje budowy przeciwwybuchowej.', a: 'Osłona ognioszczelna „d"; budowa wzmocniona „e"; budowa iskrobezpieczna „i"; osłona olejowa „o".' },
  { q: 'Podaj najważniejsze zagadnienia, które porusza Ustawa – Prawo energetyczne z dnia 10.04.1997 r.', a: 'Ustawa reguluje zasady kształtowania polityki energetycznej państwa, zasady i warunki zaopatrzenia i użytkowania paliw i energii, działalność przedsiębiorstw energetycznych, koncesjonowanie, taryfy, zasady przyłączania do sieci oraz obowiązki odbiorców.' },
  { q: 'Podaj nazwy najważniejszych aktów prawnych, których postanowienia powinny być znane każdemu pracownikowi (w tym elektrykowi).', a: 'Prawo energetyczne, rozporządzenie MG w sprawie BHP przy urządzeniach energetycznych, rozporządzenie w sprawie szczegółowych zasad eksploatacji urządzeń elektroenergetycznych, Kodeks pracy oraz przepisy BHP.' },
  { q: 'Kto jest osobą uprawnioną do eksploatacji urządzeń i instalacji elektroenergetycznych?', a: 'Osoba posiadająca aktualne świadectwo kwalifikacyjne wydane przez komisję kwalifikacyjną (np. przy SEP) po zdaniu egzaminu, uprawniające do zajmowania się eksploatacją urządzeń na stanowisku E (eksploatacja) lub D (dozór).' },
  { q: 'Podaj różnicę pomiędzy osobą uprawnioną a upoważnioną do eksploatacji urządzeń elektroenergetycznych.', a: 'Osoba uprawniona posiada świadectwo kwalifikacyjne; osoba upoważniona to pracownik, który otrzymał pisemne upoważnienie od pracodawcy do wykonania określonych czynności pod nadzorem osoby uprawnionej.' },
  { q: 'Wymień rodzaje poleceń.', a: 'Polecenie pisemne, polecenie ustne, polecenie w formie komunikatu elektronicznego z potwierdzeniem.' },
  { q: 'Kto może zajmować się eksploatacją urządzeń elektroenergetycznych?', a: 'Osoba pełnoletnia posiadająca aktualne świadectwo kwalifikacyjne odpowiedniej grupy (G1) i rodzaju (E lub D), przeszkolona w zakresie BHP oraz zapoznana z instrukcją stanowiskową.' },
  { q: 'Na kim spoczywa obowiązek wyposażenia stanowisk pracy w instrukcje eksploatacyjne?', a: 'Na pracodawcy lub osobie kierującej pracownikami (zgodnie z Kodeksem pracy i przepisami szczegółowymi).' },
  { q: 'Kiedy instrukcje eksploatacyjno-obsługowe nabierają ważności?', a: 'Z dniem zatwierdzenia przez pracodawcę i wprowadzenia do stosowania, po zapoznaniu z nimi pracowników.' },
  { q: 'Jakie znasz sposoby poprawy bezpieczeństwa pracy przy eksploatacji urządzeń i instalacji elektroenergetycznych?', a: 'Sposoby: organizacyjny (szkolenia, instrukcje, polecenia, nadzór) i techniczny (zabezpieczenia, sprzęt ochronny, wyłączenia, uziemienia, blokady).' },
  { q: 'Omów sposób organizacyjny.', a: 'Odpowiednie kwalifikacje pracowników, szkolenia BHP, instrukcje stanowiskowe, system poleceń, wyznaczanie nadzoru, dopuszczanie do pracy, koordynacja pracowników.' },
  { q: 'Omów sposób techniczny.', a: 'Wyłączenie napięcia, zabezpieczenie przed przypadkowym załączeniem, sprawdzenie braku napięcia, uziemienie i zwarcie, odgrodzenie części czynnych, stosowanie sprzętu ochronnego.' },
  { q: 'Kto to jest poleceniodawca?', a: 'Osoba uprawniona do wydawania poleceń na wykonanie prac, posiadająca świadectwo kwalifikacyjne co najmniej D i upoważniona przez pracodawcę.' },
  { q: 'Kto wyznacza koordynującego, dopuszczającego, nadzorującego, kierownika robót i kierującego zespołem?', a: 'Pracodawca lub osoba kierująca, zgodnie z instrukcją eksploatacyjną i przepisami wewnętrznymi.' },
  { q: 'Na jakie polecenie wykonuje się prace zaliczane do niebezpiecznych w energetyce?', a: 'Na polecenie pisemne (dopuszcza się także formę elektroniczną z potwierdzeniem odbioru).' },
  { q: 'Co powinno zawierać polecenie pisemne?', a: 'Miejsce i zakres pracy, termin wykonania, skład zespołu, kierownika, środki ochrony, warunki wyłączeń, podpisy wydającego i przyjmującego.' },
  { q: 'Podaj graniczną temperaturę w miejscu pracy określoną w rozporządzeniu Ministra Gospodarki z dnia 17.09.1999 r.', a: 'Nie mniej niż -5°C i nie więcej niż +30°C (zależnie od rodzaju czynności).' },
  { q: 'Jakich środków gaśniczych należy używać do gaszenia urządzeń elektrycznych będących pod napięciem?', a: 'Gaśnice proszkowe, śniegowe (CO₂), halonowe. Nie wolno używać wody ani piany.' },
  { q: 'Jak dzielimy sprzęt ochronny w zależności od przeznaczenia?', a: 'Na: sprzęt izolacyjny, sprzęt ochrony przed łukiem elektrycznym, sprzęt do ochrony przed upadkiem z wysokości, sprzęt sygnalizacyjny i ostrzegawczy, sprzęt diagnostyczny.' },
  { q: 'Wymień sprzęt izolacyjny podstawowy do 1 kV.', a: 'Rękawice izolacyjne, narzędzia izolowane, wskaźniki napięcia do 1 kV, maty izolacyjne.' },
  { q: 'Wymień sprzęt izolacyjny podstawowy powyżej 1 kV.', a: 'Pręty izolacyjne, wskaźniki napięcia powyżej 1 kV, rękawice izolacyjne, drabiny izolacyjne.' },
  { q: 'Wymień sprzęt dodatkowy do 1 kV i powyżej 1 kV.', a: 'Do 1 kV: obuwie izolacyjne, kalosze, maty izolacyjne. Powyżej 1 kV: rękawice izolacyjne, obuwie izolacyjne, kaski ochronne.' },
  { q: 'Jakie są warunki stosowania sprzętu izolacyjnego ochronnego?', a: 'Sprzęt musi być dopuszczony do użytkowania, oznakowany, sprawdzony wizualnie przed użyciem, poddawany okresowym próbom, przechowywany w suchym miejscu.' },
  { q: 'Na czym polega prawidłowa gospodarka sprzętem ochronnym i kto za nią odpowiada?', a: 'Prowadzenie ewidencji, oznakowanie, terminy badań, przechowywanie. Odpowiada pracodawca.' },
  { q: 'Co powinna sprawdzić osoba zamierzająca użyć sprzętu izolacyjnego?', a: 'Stan zewnętrzny (brak uszkodzeń), datę ostatniej próby, oznakowanie, czystość i suchość.' },
  { q: 'Podaj definicję prądu elektrycznego.', a: 'Uporządkowany ruch ładunków elektrycznych w obwodzie zamkniętym, wywołany różnicą potencjałów.' },
  { q: 'Jak definiujemy prąd stały, zmienny i przemienny?', a: 'Prąd stały (DC) – nie zmienia kierunku ani wartości. Prąd zmienny – zmienia wartość. Prąd przemienny (AC) – zmienia kierunek i wartość okresowo.' },
  { q: 'Podaj definicję napięcia elektrycznego.', a: 'Różnica potencjałów elektrycznych między dwoma punktami obwodu.' },
  { q: 'Jakie są jednostki natężenia i napięcia prądu elektrycznego?', a: 'Natężenie: amper (A). Napięcie: wolt (V).' },
  { q: 'O czym mówi prawo Ohma?', a: 'I = U/R – natężenie prądu jest wprost proporcjonalne do napięcia, a odwrotnie proporcjonalne do rezystancji.' },
  { q: 'Co to jest obwód elektryczny?', a: 'Zestaw połączonych elementów elektrycznych tworzących zamkniętą drogę dla przepływu prądu.' },
  { q: 'Z jakich elementów zbudowany jest obwód elektryczny?', a: 'Źródło energii, odbiornik, przewody łączące, elementy zabezpieczające i sterujące.' },
  { q: 'O czym mówi I prawo Kirchhoffa?', a: 'Suma prądów wpływających do węzła równa się sumie prądów wypływających.' },
  { q: 'Jakiego obwodu dotyczy II prawo Kirchhoffa?', a: 'Oczka obwodu – suma spadków napięć w oczku równa się sumie sił elektromotorycznych.' },
  { q: 'Co nazywamy mocą i energią prądu elektrycznego?', a: 'Moc (P=U×I) – praca w jednostce czasu [W]. Energia (W=P×t) – praca w czasie [kWh].' },
  { q: 'O czym mówi prawo Joule\'a-Lenza?', a: 'Ciepło wydzielone w przewodniku: Q = I² × R × t.' },
  { q: 'Co to jest akumulator?', a: 'Odwracalne chemiczne źródło prądu, które może być wielokrotnie ładowane i rozładowywane.' },
  { q: 'Podaj kryteria doboru przekroju przewodów elektrycznych.', a: 'Obciążalność prądowa, spadek napięcia, wytrzymałość mechaniczna, wytrzymałość zwarciowa, ochrona przeciwporażeniowa.' },
  { q: 'Podaj graniczne wartości natężenia prądu przemiennego i stałego, które nie powodują obrażeń u człowieka.', a: 'AC: < 10 mA, DC: < 30 mA (przy krótkim czasie przepływu).' },
  { q: 'Podaj wartości napięć bezpiecznych w zależności od rodzaju napięcia i warunków środowiskowych.', a: 'Suche: do 50V AC i 120V DC. Wilgotne: do 25V AC i 60V DC. Szczególnie niebezpieczne: do 12V AC i 30V DC.' },
  { q: 'Prąd o jakim przebiegu czasowym jest bardziej niebezpieczny dla człowieka?', a: 'Prąd przemienny (AC) 50-60 Hz – łatwiej wywołuje migotanie komór serca.' },
  { q: 'Co to jest część czynna i części jednocześnie dostępne urządzenia?', a: 'Część czynna – element pod napięciem w normalnej pracy. Części jednocześnie dostępne – części przewodzące w zasięgu ręki.' },
  { q: 'Od czego zależą skutki porażenia prądem elektrycznym?', a: 'Od wartości prądu, czasu przepływu, drogi przez ciało, częstotliwości, stanu skóry i zdrowia.' },
  { q: 'Co to jest napięcie rażenia?', a: 'Napięcie występujące między częściami czynnymi a ziemią, mogące spowodować przepływ prądu przez ciało.' },
  { q: 'Co to jest napięcie krokowe?', a: 'Napięcie między dwoma punktami na ziemi oddalonymi o krok, w strefie rażenia wokół miejsca zwarcia doziemnego.' },
  { q: 'Ile wynosi rezystancja ciała człowieka?', a: 'Od 500 Ω do kilku kΩ, zależnie od warunków. Do obliczeń przyjmuje się 1000 Ω.' },
  { q: 'Wymień klasy ochronności urządzeń i scharakteryzuj je.', a: 'Klasa 0 – tylko izolacja podstawowa. Klasa I – izolacja + PE. Klasa II – podwójna izolacja. Klasa III – napięcie bezpieczne ≤ 50V AC.' },
  { q: 'Co zaliczamy do środków ochrony przeciwporażeniowej?', a: 'Ochronę podstawową (izolacja, obudowy) i ochronę przy uszkodzeniu (RCD, uziemienia, połączenia wyrównawcze, SELV/PELV).' },
  { q: 'Jak realizowana jest ochrona podstawowa?', a: 'Przez izolowanie części czynnych, obudowy, osłony, bariery, ogrodzenia, umieszczanie poza zasięgiem ręki.' },
  { q: 'Wymień środki ochrony przed dotykiem pośrednim.', a: 'Samoczynne wyłączenie (RCD, bezpieczniki), uziemienie ochronne, połączenia wyrównawcze, separacja, urządzenia II klasy, SELV/PELV.' },
  { q: 'Co to jest uziemienie ochronne?', a: 'Połączenie części przewodzących z uziomem w celu obniżenia napięcia dotykowego i zadziałania zabezpieczeń.' },
  { q: 'Na czym polega separacja odbiornika?', a: 'Zasilanie odbiornika z transformatora separacyjnego, którego uzwojenie wtórne nie ma połączenia z ziemią.' },
  { q: 'Ile powinna wynosić rezystancja między uzwojeniami transformatora separacyjnego?', a: '≥ 5 MΩ przy 500V DC.' },
  { q: 'Wymień rodzaje układów sieciowych.', a: 'TN-C, TN-S, TN-C-S, TT, IT.' },
  { q: 'Jakim kolorem oznaczamy przewód neutralny N, a jakim ochronny PE?', a: 'N – niebieski; PE – żółto-zielony; PEN – żółto-zielony z niebieskimi oznaczeniami na końcach.' },
  { q: 'Jakim symbolem oznacza się odbiorniki w II klasie ochronności?', a: 'Symbolem podwójnego kwadratu (kwadrat w kwadracie).' },
  { q: 'W jakim celu wykonuje się prace kontrolno-pomiarowe?', a: 'W celu sprawdzenia stanu technicznego, skuteczności ochrony przeciwporażeniowej, pomiaru rezystancji izolacji, impedancji pętli zwarcia, sprawdzenia RCD.' },
  { q: 'Czy stosowanie Polskich Norm jest obowiązkowe?', a: 'Jest dobrowolne, chyba że norma jest powołana w rozporządzeniu lub umowie.' },
  { q: 'Co określają warunki przyłączenia do sieci i jak długo są ważne?', a: 'Miejsce przyłączenia, moc, napięcie, układ sieci. Ważne 2 lata.' },
  { q: 'Jakie mogą być odchylenia napięcia i częstotliwości w dostawie energii elektrycznej?', a: 'Napięcie: ±10% Un. Częstotliwość: ±1% (49,5-50,5 Hz).' },
  { q: 'Kiedy odbiorca może żądać sprawdzenia układu pomiarowego i kto ponosi koszty?', a: 'Gdy podejrzewa nieprawidłowości. Koszty ponosi odbiorca jeśli układ jest sprawny, w przeciwnym razie – dostawca.' },
  { q: 'Jak dzielimy urządzenia w wykonaniu przeciwwybuchowym?', a: 'Grupa I (kopalnie) i grupa II (pozostałe zakłady), z kategoriami 1G/2G/3G i 1D/2D/3D.' },
  { q: 'Jakie są rodzaje wykonań urządzeń elektrycznych przeciwwybuchowych?', a: 'Ognioszczelne (Ex d), wzmocnione (Ex e), iskrobezpieczne (Ex i), hermetyczne (Ex n), nadciśnieniowe (Ex p).' },
  { q: 'Podaj ogólny podział funkcjonalny urządzeń elektroenergetycznych.', a: 'Źródła wytwarzania, urządzenia przesyłowe, rozdzielcze, odbiorcze, zabezpieczające i sterujące, pomiarowe.' },
  { q: 'Jakie prace można wykonywać bez polecenia?', a: 'Prace niewymagające naruszania części czynnych, np. oględziny, wymiana wkładek topikowych przez osoby uprawnione.' },
  { q: 'Podaj sposoby uwalniania porażonego prądem do 1 kV.', a: 'Wyłączyć napięcie; odciągnąć za pomocą przedmiotu izolacyjnego; odciągnąć za ubranie (nie dotykając gołymi rękoma).' },
  { q: 'Podaj sposoby uwalniania porażonego prądem powyżej 1 kV.', a: 'Wyłączyć napięcie przez uprawnionego operatora. Nie zbliżać się bez sprzętu izolacyjnego.' },
  { q: 'Co zrobić po uwolnieniu porażonego spod napięcia?', a: 'Sprawdzić przytomność i oddech, wezwać pomoc (112), RKO 30:2, do przyjazdu pomocy.' },
  { q: 'Jaką metodę sztucznego oddychania stosujemy?', a: 'Metodę usta-usta z masażem serca (RKO), stosunek 30:2.' },
  { q: 'Podaj schemat czynności RKO (usta-usta i masaż serca).', a: 'Bezpieczeństwo → przytomność → pomoc → udrożnij drogi oddechowe → sprawdź oddech → 30 uciśnięć (5-6 cm, 100-120/min) → 2 wdechy → kontynuuj.' },
  { q: 'Podaj pięć zasad bezpieczeństwa przy pracach konserwacyjnych urządzeń elektrycznych.', a: '1) Wyłączyć napięcie. 2) Zabezpieczyć przed załączeniem. 3) Sprawdzić brak napięcia. 4) Uziemić i zewrzeć. 5) Osłonić strefę bezpieczną.' },
  { q: 'Co to jest jednostka napięcia?', a: 'Wolt (V).' },
  { q: 'Jak zmieniamy obroty w silniku trójfazowym?', a: 'Zmieniając częstotliwość (falownik) lub liczbę par biegunów (przełącznik gwiazda/trójkąt).' },
  { q: 'Co to jest wyłącznik różnicowoprądowy?', a: 'Urządzenie zabezpieczające przed porażeniem, wyłączające obwód przy wykryciu różnicy prądów (upływu).' },
  { q: 'Co to jest transformator?', a: 'Urządzenie służące do zmiany poziomu napięcia prądu przemiennego.' },
  { q: 'Co to jest wyłącznik nadprądowy?', a: 'Zabezpieczenie przed skutkami przeciążenia i zwarcia ("eska").' },
  { q: 'Co to jest ogranicznik przepięć?', a: 'Urządzenie chroniące instalację przed przepięciami atmosferycznymi i łączeniowymi.' },
  { q: 'Co to jest układ sieci TN-C?', a: 'Układ, w którym przewód PE i N są połączone w jeden przewód PEN.' },
  { q: 'Co to jest układ sieci TN-S?', a: 'Układ, w którym przewód PE i N są prowadzone oddzielnie.' },
  { q: 'Co to jest układ sieci TN-C-S?', a: 'Układ hybrydowy – część TN-C (PEN), a od rozdzielnicy TN-S (oddzielne PE i N).' },
  { q: 'Co to jest klasa ochronności I?', a: 'Ochrona przez połączenie części przewodzących z przewodem ochronnym (PE).' },
  { q: 'Co to jest klasa ochronności II?', a: 'Ochrona przez izolację podwójną lub wzmocnioną (bez PE).' },
  { q: 'Co to jest klasa ochronności III?', a: 'Ochrona przez zasilanie napięciem bezpiecznym (SELV, ≤50V AC).' },
  { q: 'Jakie są jednostki mocy elektrycznej?', a: 'Wat (W), war (var), woltoamper (VA).' },
  { q: 'Jakie są jednostki prądu elektrycznego?', a: 'Amper (A), miliamper (mA), kiloamper (kA).' },
  { q: 'Jakie są jednostki częstotliwości?', a: 'Herc (Hz).' },
  { q: 'Co to jest woltomierz i jak się go włącza?', a: 'Przyrząd do pomiaru napięcia. Włącza się równolegle.' },
  { q: 'Co to jest amperomierz i jak się go włącza?', a: 'Przyrząd do pomiaru prądu. Włącza się szeregowo.' },
  { q: 'Co to jest rezystancja?', a: 'Własność przeciwstawiania się przepływowi prądu; jednostka – om (Ω).' },
  { q: 'Co to jest pojemność elektryczna?', a: 'Zdolność gromadzenia ładunku; jednostka – farad (F).' },
  { q: 'Co to jest moc czynna?', a: 'Moc zamieniana na pracę lub ciepło (P, w watach).' },
  { q: 'Co to jest moc bierna?', a: 'Moc krążąca między źródłem a odbiornikiem (Q, w varach).' },
  { q: 'Co to jest moc pozorna?', a: 'Suma geometryczna mocy czynnej i biernej (S, w VA).' },
  { q: 'Co to jest prąd przemienny?', a: 'Prąd zmieniający okresowo kierunek i wartość (AC).' },
  { q: 'Co to jest prąd stały?', a: 'Prąd płynący w jednym kierunku o stałej wartości (DC).' },
  { q: 'Co to jest przewód ochronny (PE)?', a: 'Przewód łączący części przewodzące z uziemieniem dla ochrony przeciwporażeniowej.' },
  { q: 'Co to jest przewód neutralny (N)?', a: 'Przewód połączony z punktem neutralnym transformatora.' },
  { q: 'Jakie są rodzaje gaśnic?', a: 'Proszkowe, pianowe, śniegowe (CO₂), wodne, halonowe.' },
  { q: 'Czym różni się gaśnica proszkowa od pianowej?', a: 'Proszkowa gasi przez przerwanie reakcji chemicznej (klasy A, B, C), pianowa przez odcięcie tlenu (klasy A, B). Proszkowa nadaje się do gaszenia urządzeń pod napięciem, pianowa nie.' },
  { q: 'Do czego służy manometr?', a: 'Do pomiaru ciśnienia.' },
  { q: 'Jakie ryzyko niesie za sobą prąd elektryczny?', a: 'Porażenie, oparzenia, pożar, wybuch, uszkodzenie urządzeń.' },
  { q: 'Przed przystąpieniem do wykonywania prac przy urządzeniach i instalacjach elektrycznych odłączonych od napięcia należy wykonać jakie działania przygotowawcze (5 złotych zasad)?', a: 'Wyłączyć napięcie, zabezpieczyć przed ponownym włączeniem, sprawdzić brak napięcia, uziemić i zewrzeć, osłonić sąsiednie części pod napięciem.' },
  { q: 'Na podstawie jakiego polecenia można wykonywać prace eksploatacyjne stwarzające możliwość wystąpienia szczególnego zagrożenia dla zdrowia lub życia ludzkiego?', a: 'Na podstawie Pisemnego Polecenia.' },
  { q: 'Jak długo po zakończeniu pracy wykonywanej na Pisemnego Polecenie należy przechowywać dokument?', a: '90 dni od daty zakończenia prac.' },
  { q: 'Kiedy może wystąpić napięcie krokowe i jak można ograniczyć jego wpływ?', a: 'Przy doziemieniu przewodu pod napięciem. Poruszać się małymi krokami, nie odrywając stóp od ziemi.' },
  { q: 'Czego nie wyłącza przeciwpożarowy wyłącznik prądu?', a: 'Urządzeń przeciwpożarowych (pomp, oświetlenia ewakuacyjnego, dźwigów dla straży pożarnej).' },
  { q: 'Gaśnicą z jakim czynnikiem możemy bezpiecznie gasić urządzenia pod napięciem?', a: 'Gaśnicą CO₂ (śniegową) lub proszkową.' },
  { q: 'Jak wykonujemy masaż serca?', a: '100-120 uciśnięć/min, głębokość 5-6 cm, na wysokości 1/3 mostka.' },
  { q: 'Jak długo trzeba reanimować poszkodowanego bez funkcji życiowych?', a: 'Do przybycia profesjonalnej pomocy medycznej lub wyczerpania sił ratownika.' },
  { q: 'Prace wymagające asekuracji powinny być wykonywane przez co najmniej ile osób?', a: 'Co najmniej 2 osoby.' },
  { q: 'Co powinno zawierać Polecenie Pisemne?', a: 'Numer, osoby odpowiedzialne, zakres prac, warunki i środki ochronne, termin i przerwy.' },
  { q: 'Jakie są podstawowe oznaczenia literowe przewodów?', a: 'L1, L2, L3 – fazowe; N – neutralny; PE – ochronny; PEN – ochronno-neutralny.' },
  { q: 'Jak dzielimy trasy linii wysokiego napięcia?', a: 'Na napowietrzne i kablowe (podziemne).' },
  { q: 'Co oznacza skrót SEP?', a: 'Stowarzyszenie Elektryków Polskich.' },
  { q: 'Jakie są podstawowe jednostki miary w elektryce?', a: 'Wolt (V), Amper (A), Om (Ω), Wat (W).' },
  { q: 'Co to jest uziemienie?', a: 'Połączenie instalacji lub urządzenia z ziemią dla bezpieczeństwa i ochrony przeciwporażeniowej.' },
  { q: 'Co to jest transformator?', a: 'Urządzenie do zmiany wartości napięcia prądu przemiennego.' },
  { q: 'Co to jest zwarcie?', a: 'Połączenie dwóch punktów obwodu o różnym potencjale przez bardzo małą rezystancję.' },
  { q: 'Co to jest rezystancja?', a: 'Opór, jaki stawia materiał przepływowi prądu [Ω].' },
  { q: 'Co to jest amperomierz?', a: 'Przyrząd do pomiaru natężenia prądu.' },
  { q: 'Jakie napięcie stosuje się w sieciach wysokiego napięcia?', a: 'Powyżej 1 kV (110 kV, 220 kV, 400 kV).' },
  { q: 'Co to jest pole elektryczne?', a: 'Przestrzeń wokół ładunków elektrycznych, w której działają siły elektryczne.' },
  { q: 'Jaka jest różnica między napięciem a natężeniem prądu?', a: 'Napięcie (V) to różnica potencjałów, natężenie (A) to przepływ ładunku w jednostce czasu.' },
  { q: 'Co to jest izolacja elektryczna?', a: 'Materiał nieprzewodzący, oddzielający przewody pod napięciem.' },
  { q: 'Jakie kolory mają przewody?', a: 'Fazowe: brązowy/czarny/szary; neutralny: niebieski; ochronny: żółto-zielony.' },
  { q: 'Co to jest licznik energii elektrycznej?', a: 'Przyrząd do pomiaru zużycia energii elektrycznej (kWh).' },
  { q: 'Jakie są rodzaje ochron przed porażeniem?', a: 'Ochrona podstawowa (przed dotykiem bezpośrednim) i ochrona dodatkowa (przed dotykiem pośrednim).' },
  { q: 'Co to jest odgromnik?', a: 'Urządzenie chroniące instalację przed przepięciami atmosferycznymi.' },
  { q: 'Co to jest przewodnik?', a: 'Materiał umożliwiający przepływ prądu (np. miedź, aluminium).' },
  { q: 'Co to jest prąd zwarciowy?', a: 'Prąd o bardzo dużej wartości powstały w wyniku zwarcia.' },
  { q: 'Co to jest połączenie równoległe?', a: 'Połączenie, w którym napięcie na każdym elemencie jest takie samo.' },
  { q: 'Co to jest różnicówka?', a: 'Wyłącznik różnicowoprądowy (RCD), wykrywający upływ prądu.' },
  { q: 'Jakie są podstawowe rodzaje sieci elektroenergetycznych?', a: 'nn (do 1 kV), SN (do 30 kV), WN (powyżej 30 kV).' },
  { q: 'Czym jest generator prądu?', a: 'Urządzeniem przetwarzającym energię mechaniczną na elektryczną.' },
  { q: 'Jakie są podstawowe rodzaje prądów zwarciowych?', a: 'Jednofazowe, dwufazowe, trójfazowe; symetryczne i niesymetryczne.' },
  { q: 'Jakie są rodzaje ochron przeciwporażeniowych w instalacjach niskiego napięcia?', a: 'Samoczynne wyłączenie, izolacja podwójna, separacja, SELV/PELV, połączenia wyrównawcze.' },
  { q: 'Co to jest obwód zamknięty?', a: 'Obwód, w którym prąd może płynąć (zamknięta droga przepływu).' },
  { q: 'Co to jest przekładnik prądowy?', a: 'Urządzenie do obniżenia prądu dla celów pomiarowych lub zabezpieczeniowych.' },
  { q: 'Jakie zadanie mają środki ochrony podstawowej w urządzeniach i instalacjach elektrycznych?', a: 'Zabezpieczenie przed dotykiem bezpośrednim części pod napięciem (izolacja, obudowy, bariery).' },
  { q: 'Jakie warunki musi spełniać osoba poleceniodawcy?', a: 'Posiadanie aktualnego świadectwa SEP i upoważnienia od pracodawcy.' },
  { q: 'Czy wyłącznik różnicowoprądowy zadziała w sieci dwuprzewodowej?', a: 'Nie, wymaga przewodu ochronnego (PE) – minimum 3 żyły.' },
  { q: 'Jaka jest minimalna dopuszczalna rezystancja izolacji?', a: '0,5 MΩ dla instalacji do 500V (I i III kl.), 2 MΩ dla II klasy ochronności.' },
  { q: 'Jaki kolor powinna mieć izolacja przewodu ochronnego?', a: 'Żółto-zielony.' },
  { q: 'Podaj wartość natężenia prądu niepowodującego skutku śmiertelnego?', a: 'Dla AC poniżej 10 mA, dla DC poniżej 30 mA (bezpieczny prąd rażenia).' },
  { q: 'Jakie są terminy okresowych pomiarów instalacji odgromowej?', a: 'Co 5 lat, a dla obiektów zagrożonych wybuchem – co rok.' },
  { q: 'Od czego zależą skutki przepływu prądu przez ciało?', a: 'Od wartości prądu, drogi, czasu, częstotliwości, stanu skóry i zdrowia.' },
  { q: 'Jak dzielimy transformatory ze względu na czynnik chłodzący?', a: 'Na olejowe, suche (żywiczne, powietrzne) i gazowe.' },
  { q: 'Co to jest strona pierwotna i wtórna transformatora?', a: 'Pierwotna – uzwojenie zasilające; wtórna – uzwojenie odbiorcze.' },
  { q: 'Co to jest prąd jałowy transformatora?', a: 'Prąd w uzwojeniu pierwotnym przy rozwartym uzwojeniu wtórnym (bieg jałowy).' },
  { q: 'Do czego służy wyłącznik?', a: 'Do załączania i wyłączania obwodów w warunkach normalnych i awaryjnych.' },
  { q: 'Do czego służy rozłącznik?', a: 'Do załączania i wyłączania prądów roboczych (nie przerywa zwarć).' },
  { q: 'Do czego służy odłącznik?', a: 'Do odłączania napięcia – stwarza widoczną przerwę izolacyjną (łączy bez obciążenia).' },
  { q: 'Do czego służą odgromniki?', a: 'Do ochrony urządzeń przed przepięciami.' },
  { q: 'Kiedy można załączyć linię kablową po przerwie >30 dni?', a: 'Po sprawdzeniu rezystancji izolacji z wynikiem pozytywnym.' },
  { q: 'Jakie próby należy wykonać po naprawie linii kablowej?', a: 'Sprawdzenie ciągłości żył, zgodności faz, rezystancji izolacji, próba napięciowa.' },
  { q: 'Czym można gasić palące się kable?', a: 'Piaskiem, gaśnicą proszkową lub śniegową (po wyłączeniu napięcia).' },
  { q: 'Podaj wymagania kwalifikacyjne dla osób przy eksploatacji urządzeń elektroenergetycznych?', a: 'Świadectwo kwalifikacyjne SEP, szkolenie BHP, znajomość przepisów.' },
  { q: 'Kogo obowiązuje ewidencja wydanych poleceń?', a: 'Poleceniodawcę.' },
  { q: 'Kto to jest kierownik robót?', a: 'Osoba wyznaczona do koordynacji prac, gdy w obiekcie pracuje więcej niż jeden zespół.' },
  { q: 'Co powinno się określać w poleceniu wykonania pracy?', a: 'Zakres, rodzaj, miejsce, termin, środki, liczbę pracowników, osoby odpowiedzialne.' },
  { q: 'Kto może wystąpić z wnioskiem o powtórzenie egzaminu?', a: 'Pracodawca, Inspektor Pracy, Prezes URE.' },
  { q: 'Jakie zjawiska są najczęściej przyczyną zwarć?', a: 'Przepięcia atmosferyczne i łączeniowe, omyłki łączeniowe, długotrwałe przeciążenia.' },
  { q: 'Podaj sposoby zmniejszenia poboru mocy biernej?', a: 'Kompensacja bateriami kondensatorów, dobór silników, unikanie pracy jałowej.' },
  { q: 'Od czego zależy ilość ciepła wytwarzanego przez prąd?', a: 'Od I², R i t (prawo Joule\'a-Lenza).' },
  { q: 'Wymień urządzenia będące główną przyczyną poboru mocy biernej?', a: 'Silniki indukcyjne, transformatory, spawarki, dławiki.' },
  { q: 'Jakiej kontroli metrologicznej podlegają przyrządy pomiarowe?', a: 'Legalizacji pierwotnej, legalizacji ponownej (uwierzytelnieniu), zatwierdzenia typu.' },
  { q: 'Na czym polega kompensacja mocy biernej?', a: 'Na wytwarzaniu mocy biernej w miejscu zapotrzebowania (baterie kondensatorów).' },
  { q: 'Co nazywamy porażeniem prądem elektrycznym?', a: 'Przepływ prądu przez ciało człowieka wywołujący skutki chorobowe.' },
  { q: 'Co to są warunki środowiskowe?', a: 'Lokalne warunki zewnętrzne pracy urządzeń (temperatura, wilgotność, zapylenie).' },
  { q: 'W jakim celu stosuje się oznakowanie przewodów?', a: 'Dla bezpieczeństwa, łatwej identyfikacji i uniknięcia pomyłek.' },
  { q: 'Co wchodzi w skład sprzętu zabezpieczającego i ostrzegawczego?', a: 'Pasy bezpieczeństwa, uziemiacze, ubrania trudnopalne, hełmy, tablice bezpieczeństwa.' },
  { q: 'Jakie czynności wykonuje ratownik, gdy porażony jest przytomny?', a: 'Ułożyć wygodnie, rozluźnić ubranie, obejrzeć, wezwać pomoc.' },
  { q: 'Jakie stany mogą wystąpić u porażonego?', a: 'Oddychanie prawidłowe; brak oddechu ale krążenie utrzymane; brak oddechu i krążenia.' },
  { q: 'W jakich miejscach stosować wyłączniki RCD 30 mA?', a: 'W łazience, kuchni, garażu, piwnicy – obwody gniazd wtyczkowych.' },
  { q: 'Po ilu minutach szansa uratowania porażonego równa się zeru?', a: 'Po 5 minutach.' },
  { q: 'Jakie zjawiska mogą być przyczyną pożarów?', a: 'Przepływ prądów roboczych i zwarciowych, łuk elektryczny, zwiększona rezystancja styków, przepięcia.' },
  { q: 'Jakie są skutki nadmiernego nagrzewania przewodów?', a: 'Przegrzanie izolacji, spalenie, stopienie, pożar.' },
  { q: 'Jak gasić palące się silniki elektryczne?', a: 'Wyłączyć napięcie, gasić gaśnicą śniegową lub proszkową.' },
  { q: 'Jak gasić rozdzielnice?', a: 'Gaśnicą śniegową lub proszkową po wyłączeniu napięcia (odległość min. 1 m).' },
  { q: 'Jakim obrażeniom ulega człowiek od łuku elektrycznego?', a: 'Oparzenia, uszkodzenia mechaniczne, zapalenie odzieży, uszkodzenie wzroku.' },
  { q: 'Jak wyłączyć napięcie w celu uwolnienia porażonego?', a: 'Otworzyć łączniki, wyjąć wkładki topikowe, zwarć przewody w liniach napowietrznych.' },
  { q: 'Jaki materiał izolujący stosuje się przy uwalnianiu do 1 kV?', a: 'Sprzęt izolacyjny; w razie braku – suche drewno, tworzywa sztuczne, suche tkaniny.' },
  { q: 'Co to są linie napowietrzne i jakie przepisy regulują ich budowę?', a: 'Urządzenia do przesyłu energii przewodami zawieszonymi na słupach. Normy: PN-E-05100-1, N SEP-E-003.' },
  { q: 'Jak dzielimy linie napowietrzne ze względu na napięcie?', a: 'nn (do 1 kV), SN (1-35 kV), WN (35-230 kV), NWN (>230 kV).' },
  { q: 'Jakie są podstawowe elementy linii napowietrznych?', a: 'Przewody, izolatory, konstrukcje wsporcze, osprzęt liniowy.' },
  { q: 'Jakie przewody stosuje się w liniach nn?', a: 'Gołe linki aluminiowe (AL.) oraz izolowane przewody samonośne (AsXS).' },
  { q: 'Jak dzielimy słupy linii napowietrznych ze względu na funkcję?', a: 'Przelotowe (P), narożne (N), mocne (M), odporowe (O), krańcowe (K), rozgałęźne (R).' },
  { q: 'Jak dzielimy słupy do 1 kV ze względu na budowę?', a: 'Drewniane, betonowe (żerdzie), stalowe (kratowe, blaszane).' }
];
