const questionsFGazy = [
  { q: 'Jednostk─ů temperatury w uk┼éadzie SI jest:', a: 'K (kelwin)' },
  { q: 'W czasie procesu parowania, czynnik ch┼éodniczy:', a: 'absorbuje ciep┼éo' },
  { q: 'Zaw├│r rozpr─Ö┼╝ny w uk┼éadzie ch┼éodniczym:', a: 'w pewnym zakresie reguluje warto┼Ť─ç przegrzania czynnika na wyj┼Ťciu z parownika' },
  { q: 'Wad─ů w─Öglowodor├│w jest ich palno┼Ť─ç, kt├│ra lokuje te substancje w grupie bezpiecze┼ästwa:', a: 'A3' },
  { q: 'W raporcie o stanie termostatycznego zaworu rozpr─Ö┼╝nego:', a: 'nale┼╝y umie┼Ťci─ç informacje o strojeniu warto┼Ťci przegrzewu, je┼Ťli by┼éo wykonane' },
  { q: 'Spr─Ö┼╝arka hermetyczna:', a: 'posiada silnik i spr─Ö┼╝ark─Ö zamkni─Öte w hermetycznej obudowie' },
  { q: 'Skraplacz w uk┼éadzie ch┼éodniczym:', a: 'po┼Ťredniczy w odbieraniu ciep┼éa od czynnika ch┼éodniczego w przemianie zwanej skraplaniem' },
  { q: 'Zawory odcinaj─ůce (kulowe lub grzybkowe):', a: 's┼éu┼╝─ů do odcinania element├│w lub fragment├│w uk┼éadu ch┼éodniczego' },
  { q: 'W karcie urz─ůdzenia wpisujemy:', a: 'zakres przeprowadzonej kontroli szczelno┼Ťci' },
  { q: 'Parownik urz─ůdzenia ch┼éodniczego mo┼╝e by─ç rozmra┼╝any:', a: 'grza┼ék─ů elektryczn─ů' },
  { q: 'Wzrost przegrzewu pary na kolektorze ssawnym spr─Ö┼╝arki skutkuje:', a: 'wzrostem temperatury ko┼äca t┼éoczenia' },
  { q: 'Po┼é─ůczenie lutowane mo┼╝e by─ç miejscem wycieku:', a: 'w przypadku p─Ökni─Öcia lutu na skutek drga┼ä' },
  { q: 'Czujniki temperatury na ruroci─ůgu ch┼éodniczym mog─ů by─ç montowane w spos├│b:', a: 'przylgowy lub kieszeniowy' },
  { q: 'Okre┼Ťlenie ODP dotyczy:', a: 'substancji zuba┼╝aj─ůcych warstw─Ö ozonow─ů' },
  { q: 'Pojemnik s┼éu┼╝─ůcy do przechowywania F-gaz├│w musi posiada─ç etykiet─Ö z min. informacjami:', a: 'typ i rodzaj F-gazu' },
  { q: 'Specyfikacja fluorowanych gaz├│w cieplarnianych:', a: 'znajduje si─Ö w za┼é─ůczniku do rozporz─ůdzenia UE (WE) nr 517/2014' },
  { q: 'Stosowanie uk┼éad├│w nadkrytycznych:', a: 'jest mniej korzystne pod wzgl─Ödem efektywno┼Ťci energetycznej' },
  { q: 'Karta urz─ůdzenia zawiera m.in.:', a: 'ilo┼Ť─ç odzyskanego fluorowanego gazu cieplarnianego' },
  { q: 'W karcie urz─ůdzenia wpisujemy:', a: 'ilo┼Ť─ç, rodzaj i GWP czynnika ch┼éodniczego umieszczonego w urz─ůdzeniu' },
  { q: 'Wydajno┼Ť─ç skraplacza powietrznego mo┼╝na regulowa─ç:', a: 'np. poprzez za┼é─ůczenie lub wy┼é─ůczanie wentylator├│w' },
  { q: 'Czynnik R-744/CO2 charakteryzuje si─Ö:', a: 'nisk─ů temperatur─ů krytyczn─ů (ok 30┬░C) w zwi─ůzku z tym prac─ů w trybie pod i nadkrytycznym' },
  { q: 'W lamelowym parowniku powietrznym rozdzia┼é czynnika odbywa si─Ö poprzez:', a: 'rozdzielacz czynnika' },
  { q: 'Podmiot kt├│ry wwozi F-gazy na terytorium RP ma obowi─ůzek z┼éo┼╝y─ç:', a: 'sprawozdanie do Urz─Ödu Skarbowego w┼éa┼Ťciwego dla miejsca rejestracji podmiotu' },
  { q: 'Montowanie sta┼éego uk┼éadu wykrywania wyciek├│w:', a: 'pozwala zmniejszy─ç ilo┼Ť─ç wyciek├│w' },
  { q: 'W karcie urz─ůdzenia wpisujemy:', a: 'ilo┼Ť─ç i rodzaj oleju zanieczyszczonego F-gazem kt├│ry zosta┼é odzyskany z instalacji' },
  { q: 'W raporcie o stanie spr─Ö┼╝arki:', a: 'nale┼╝y umie┼Ťci─ç informacje o poborze pr─ůdu w ustalonym stanie pracy spr─Ö┼╝arki' },
  { q: 'W raporcie o stanie skraplacza powietrznego:', a: 'nale┼╝y umie┼Ťci─ç informacje o przeprowadzonym czyszczeniu bloku lamelowego' },
  { q: 'W raporcie o stanie lamelowego parownika powietrznego:', a: 'nale┼╝y umie┼Ťci─ç informacj─Ö o usuwaniu nadmiaru lodu' },
  { q: 'Jednym z alternatywnych czynnik├│w (R600A) jest:', a: 'izobutan' },
  { q: 'Redukowanie mocy ch┼éodniczej urz─ůdze┼ä:', a: 'skutkuje zmniejszeniem nape┼énienia i jest metod─ů zmniejszenia stosowania F-gaz├│w' },
  { q: 'Jednostk─ů masy w uk┼éadzie SI jest:', a: 'kg' },
  { q: 'Wska┼║nik wilgoci w uk┼éadzie:', a: 'wskazuje obecno┼Ť─ç wilgoci i konieczno┼Ť─ç wymiany filtra odwadniacza' },
  { q: 'Separator cieczy:', a: 'pozwala zapobiec zasysaniu kropel cieczy przez spr─Ö┼╝ark─Ö' },
  { q: 'Sprawozdania z art. 39 ustawy z dnia 15 maja 2015:', a: 's─ů przekazywane w postaci formularzy elektronicznych' },
  { q: 'Pa┼ästwa cz┼éonkowskie, kt├│re ratyfikowa┼éy protok├│┼é z Kioto:', a: 'zobowi─ůza┼éy si─Ö do redukcji emisji gaz├│w cieplarnianych' },
  { q: 'Okre┼Ťlenie F-gaz odnosi si─Ö do:', a: 'wodorofluorow─Öglowodor├│w (HFC), perfluorow─Öglowodor├│w (PFC) i heksafluorku siarki SF6' },
  { q: 'W czasie pracy uk┼éadu, w spr─Ö┼╝arce ch┼éodniczej, para czynnika:', a: 'podgrzewa si─Ö' },
  { q: 'Karta urz─ůdzenia zawiera min.:', a: 'dane operatora urz─ůdzenia' },
  { q: 'Skr─Öcone po┼é─ůczenie ruroci─ůgu mo┼╝e by─ç miejscem wycieku w przypadku:', a: 'poluzowania si─Ö nakr─Ötki na gwincie' },
  { q: 'Metod─ů zmniejszenia emisji F-gaz├│w jest:', a: 'zwi─Ökszenie cz─Östotliwo┼Ťci kontroli szczelno┼Ťci' },
  { q: 'W zanieczyszczonym skraplaczu powietrznym:', a: 'spada wsp├│┼éczynnik przewodzenia ciep┼éa' },
  { q: 'Jednostk─ů ci┼Ťnienia w uk┼éadzie SI jest:', a: 'Pa (paskal)' },
  { q: 'Spr─Ö┼╝arka w uk┼éadzie ch┼éodniczym:', a: 'spr─Ö┼╝a czynnik ch┼éodniczy' },
  { q: 'Parownik w uk┼éadzie ch┼éodniczym:', a: 'po┼Ťredniczy w absorbowaniu ciep┼éa przez czynnik ch┼éodniczy w przemianie zwanej parowaniem' },
  { q: 'Regulator ci┼Ťnienia skraplania:', a: 'utrzymuje ci┼Ťnienie skraplania na zadanym poziomie' },
  { q: 'Zbiornik cieczy w uk┼éadzie ch┼éodniczym s┼éu┼╝y do:', a: 'kompensacji zmiennej ilo┼Ťci cyrkuluj─ůcego czynnika w uk┼éadzie' },
  { q: 'Efekt cieplarniany to zjawisko polegaj─ůce na:', a: 'podnoszeniu si─Ö ┼Ťredniej temperatury atmosfery ziemskiej' },
  { q: 'Protok├│┼é z ci┼Ťnieniowej pr├│by szczelno┼Ťci zawiera m.in.:', a: 'pocz─ůtkowe oraz ko┼äcowe ci┼Ťnienia i temperatury pr├│by' },
  { q: 'Urz─ůdzenie zawieraj─ůce F-gaz musi posiada─ç etykiet─Ö z:', a: 'warto┼Ťci─ů nape┼énienia w kg i ekwiwalentem CO2' },
  { q: 'Podmioty obj─Öte obowi─ůzkiem z art. 39 ustawy:', a: 'powinny zarejestrowa─ç si─Ö w Bazie Danych Sprawozda┼ä (BDS)' },
  { q: 'Termostatyczny zaw├│r rozpr─Ö┼╝ny:', a: 'dozuje czynnik ch┼éodniczy do parownika aby utrzyma─ç zadane przegrzanie' },
  { q: 'Skraplacze ze wzgl─Ödu na medium mo┼╝na podzieli─ç:', a: 'm.in. na powietrzne i wodne' },
  { q: 'Chc─ůc zastosowa─ç odtajanie parownika powietrzem obiegowym:', a: 'temperatura powietrza musi by─ç wy┼╝sza od temperatury topnienia lodu' },
  { q: 'Presostaty ci┼Ťnieniowe w uk┼éadzie ch┼éodniczym:', a: 'maj─ů za zadanie wy┼é─ůczenie spr─Ö┼╝arki gdy przekraczane s─ů ci┼Ťnienia dopuszczalne' },
  { q: 'Zawory odcinaj─ůce zbiornik cieczy:', a: 'powinny by─ç montowane jak najbli┼╝ej kr├│─çc├│w wlotowych i wylotowych zbiornika' },
  { q: 'Zbiornik cieczy pozwala na:', a: 'magazynowanie ca┼éo┼Ťci lub cz─Ö┼Ťci czynnika w czasie postoj├│w lub remont├│w' },
  { q: 'Separator oleju:', a: 'wychwytuje olej emitowany przez spr─Ö┼╝ark─Ö' },
  { q: 'Separator oleju mo┼╝e dzia┼éa─ç na zasadzie:', a: 'zbiornika w kt├│rym mieszanina pary i oleju uzyskuje ruch wirowy' },
  { q: 'Zbiornik oleju w uk┼éadzie ch┼éodniczym:', a: 'odpowiada za zapewnienie dostatecznej ilo┼Ťci oleju do smarowania spr─Ö┼╝arek' },
  { q: 'Regulator poziomu oleju w spr─Ö┼╝arce odpowiada za:', a: 'utrzymanie odpowiedniego poziomu oleju w spr─Ö┼╝arce' },
  { q: 'Proces rozmra┼╝ania mo┼╝e by─ç zako┼äczony:', a: 'po up┼éywie zadanego czasu trwania tego procesu' },
  { q: 'Proces rozmra┼╝ania mo┼╝e by─ç zako┼äczony:', a: 'po osi─ůgni─Öciu zadanej ko┼äcowej temperatury' },
  { q: 'Kt├│ry z mi─Ödzynarodowych akt├│w prawnych dotyczy substancji zubo┼╝aj─ůcych warstw─Ö ozonow─ů?', a: 'Protok├│┼é montrealski w sprawie substancji zubo┼╝aj─ůcych warstw─Ö ozonow─ů.' },
  { q: 'Kt├│ry z mi─Ödzynarodowych akt├│w prawnych dotyczy zmian klimatu?', a: 'Protok├│┼é z Kioto do Ramowej konwencji Narod├│w Zjednoczonych w sprawie zmian klimatu.' },
  { q: 'Najwa┼╝niejszym polskim aktem prawnym dotycz─ůcym SZWO oraz F-gaz├│w jest:', a: 'Ustawa z dn. 15.05.2015 r. o substancjach zubo┼╝aj─ůcych warstw─Ö ozonow─ů oraz o niekt├│rych fluorowanych gazach cieplarnianych (Dz.U. 2015 poz. 881 z p├│┼║n. zm.).' },
  { q: 'Zakaz stosowania jakich czynnik├│w obowi─ůzuje od 1 stycznia 2020 r.?', a: 'Nie wolno stosowa─ç nowych czynnik├│w o GWP powy┼╝ej 2500 do serwisowania urz─ůdze┼ä o nape┼énieniu 40t ekwiwalentu CO2 lub wi─Ökszej.' },
  { q: 'Co oznacza skr├│t HFC?', a: 'Hydrofluorow─Öglowod├│r ÔÇô czynnik ch┼éodniczy nie przyczyniaj─ůcy si─Ö do niszczenia ozonu, ale wp┼éywaj─ůcy na efekt cieplarniany.' },
  { q: 'Co oznacza skr├│t SZWO?', a: 'Substancje zubo┼╝aj─ůce warstw─Ö ozonow─ů ÔÇô pochodne w─Öglowodor├│w zawieraj─ůce chlor lub brom.' },
  { q: 'Co to s─ů substancje kontrolowane?', a: 'Substancje wymienione w za┼é─ůczniku I rozporz─ůdzenia (WE) NR 1005/2009.' },
  { q: 'Co to s─ů F-gazy?', a: 'Fluorowane gazy cieplarniane: HFC, PFC, SF6 i inne gazy zawieraj─ůce fluor.' },
  { q: 'Jakie minimalne wyposa┼╝enie powinno mie─ç certyfikowane przedsi─Öbiorstwo?', a: 'Zgodne z Rozporz─ůdzeniem Ministra Rozwoju i Finans├│w z dnia 7 grudnia 2017 r. (Dz.U. 2017 poz. 2417).' },
  { q: 'Kiedy przepisy nak┼éadaj─ů obowi─ůzek za┼éo┼╝enia Karty Urz─ůdzenia?', a: 'Dla urz─ůdze┼ä zawieraj─ůcych 3 kg lub wi─Öcej F-gaz├│w/SZWO lub co najmniej 5 ton ekwiwalentu CO2.' },
  { q: 'Czyim obowi─ůzkiem jest za┼éo┼╝enie Karty Urz─ůdzenia?', a: 'Obowi─ůzek operatora urz─ůdzenia.' },
  { q: 'Kto mo┼╝e dokonywa─ç wpis├│w w Karcie Urz─ůdzenia?', a: 'Osoby posiadaj─ůce certyfikat dla personelu.' },
  { q: 'W jakim terminie sporz─ůdza si─Ö Kart─Ö Urz─ůdzenia?', a: 'W ci─ůgu 15 dni od dostarczenia urz─ůdzenia lub zako┼äczenia instalacji.' },
  { q: 'Od czego zale┼╝y cz─Östotliwo┼Ť─ç kontroli szczelno┼Ťci?', a: 'Od ilo┼Ťci ekwiwalentu CO2: 5-50t CO2 eq ÔÇô co 12/24 mies.; 50-500t ÔÇô co 6/12 mies.; powy┼╝ej 500t ÔÇô co 3/6 mies.' },
  { q: 'Jakimi metodami mo┼╝na dokona─ç pomiaru szczelno┼Ťci?', a: 'Metod─ů po┼Ťredni─ů lub bezpo┼Ťredni─ů.' },
  { q: 'Na czym polega metoda po┼Ťrednia?', a: 'Kontrola wzrokowa i r─Öczna oraz analiza ci┼Ťnienia, temperatury, pr─ůdu, poziom├│w p┼éyn├│w.' },
  { q: 'Na czym polega metoda bezpo┼Ťrednia?', a: 'U┼╝ycie urz─ůdzenia wykrywaj─ůcego gaz, p┼éynu detekcyjnego, barwnika, mydlin.' },
  { q: 'Kogo dotyczy Certyfikat dla personelu?', a: 'Os├│b wykonuj─ůcych: kontrol─Ö szczelno┼Ťci, odzysk, instalacj─Ö, napraw─Ö, konserwacj─Ö, serwisowanie, likwidacj─Ö.' },
  { q: 'Jakie wymagania musi spe┼énia─ç osoba staraj─ůca si─Ö o Certyfikat personelu?', a: 'Pe┼énoletnia, niekarana za przest─Öpstwa przeciwko ┼Ťrodowisku, po zdanym egzaminie.' },
  { q: 'Kiedy nale┼╝y uzyska─ç Certyfikat dla przedsi─Öbiorstwa?', a: 'Przy instalacji, naprawie, konserwacji, serwisowaniu lub likwidacji urz─ůdze┼ä F-gaz.' },
  { q: 'Jakie procedury musi posiada─ç przedsi─Öbiorstwo?', a: 'Procedur─Ö instalacji, likwidacji, odzysku oraz konserwacji, naprawy lub serwisowania.' },
  { q: 'Jaki zakaz dot. SZWO obowi─ůzuje od 01.01.2015?', a: 'Ca┼ékowity zakaz serwisowania urz─ůdze┼ä zawieraj─ůcych SZWO.' },
  { q: 'Jakim kodem odpadu oznakowuje si─Ö CFC, HCFC, HFC?', a: '14 06 01*' },
  { q: 'Co to jest temperatura?', a: 'Miara energii cz─ůstek cia┼éa wywo┼éanej dop┼éywem ciep┼éa.' },
  { q: '0┬░C to ile Kelwin├│w?', a: '273,15 K' },
  { q: 'Co to jest ci┼Ťnienie?', a: 'Si┼éa naporu dzia┼éaj─ůca prostopadle do powierzchni, oznaczana p [Pa].' },
  { q: 'Paskal [Pa] to:', a: 'stosunek si┼éy 1 N do powierzchni 1 m┬▓.' },
  { q: 'Co to jest masa?', a: 'W┼éa┼Ťciwo┼Ť─ç materii okre┼Ťlaj─ůca op├│r przy zmianie ruchu.' },
  { q: 'Co to jest g─Östo┼Ť─ç?', a: 'Masa jednostki obj─Öto┼Ťci cia┼éa.' },
  { q: 'Z jakich element├│w sk┼éada si─Ö podstawowe urz─ůdzenie zi─Öbi─ůce?', a: 'Spr─Ö┼╝arka, skraplacz, parownik, zaw├│r rozpr─Ö┼╝ny.' },
  { q: 'Co to jest entalpia?', a: 'Wielko┼Ť─ç fizyczna b─Öd─ůca sum─ů energii wewn─Ötrznej i iloczynu pV.' },
  { q: 'Jak klasyfikujemy substancje w urz─ůdzeniach ch┼éodniczych?', a: 'Syntetyczne (jednorodne, mieszaniny) i naturalne (organiczne, nieorganiczne).' },
  { q: 'Co to s─ů mieszaniny zeotropowe?', a: 'Mieszaniny o r├│┼╝nej lotno┼Ťci, wykazuj─ů po┼Ťlizg temperaturowy.' },
  { q: 'Co to s─ů mieszaniny azeotropowe?', a: 'Mieszaniny w r├│wnowadze termodynamicznej ÔÇô sk┼éad pary i cieczy taki sam.' },
  { q: 'Jak dzielimy spr─Ö┼╝arki?', a: 'Na przep┼éywowe i wyporowe; wyporowe na t┼éokowe i rotacyjne.' },
  { q: 'Co to jest stopie┼ä spr─Ö┼╝ania?', a: 'Iloraz ko┼äcowego ci┼Ťnienia spr─Ö┼╝arki do ci┼Ťnienia ssania.' },
  { q: 'Jak dzia┼éa spr─Ö┼╝arka hermetyczna t┼éokowa?', a: 'Obudowa spawana, silnik i spr─Ö┼╝arka na wsp├│lnym wale, ch┼éodzona zasysanym czynnikiem.' },
  { q: 'Jak dzia┼éa spr─Ö┼╝arka p├│┼éhermetyczna?', a: '┼ü─ůczy cechy otwartej i hermetycznej ÔÇô mo┼╝liwo┼Ť─ç remont├│w, smarowanie ci┼Ťnieniowe.' },
  { q: 'Jak dzia┼éa spr─Ö┼╝arka spiralna?', a: 'Dwie spirale nad silnikiem, gaz ch┼éodzi silnik i jest spr─Ö┼╝any mi─Ödzy spiralami.' },
  { q: 'Jak dzieli si─Ö parowniki?', a: 'Do ch┼éodzenia cieczy, powietrza (ch┼éodnice) i cia┼é sta┼éych.' },
  { q: 'Wymie┼ä metody odszraniania parownika:', a: 'naturalne, elektryczne, gor─ůcymi parami czynnika.' },
  { q: 'Om├│w zasad─Ö dzia┼éania skraplacza:', a: 'Odprowadza ciep┼éo pobrane w parowniku + ciep┼éo spr─Ö┼╝ania, para skrapla si─Ö oddaj─ůc ciep┼éo.' },
  { q: 'Wymie┼ä rodzaje skraplaczy:', a: 'powietrzne, wodne, wyparne, p┼éytowe, wsp├│┼éosiowe.' },
  { q: 'Czym charakteryzuje si─Ö skraplacz natryskowo-wyparny?', a: 'Ch┼éodzony powietrzem i wod─ů natryskiwan─ů przeciwpr─ůdowo.' },
  { q: 'Na czym polega regulacja ci┼Ťnienia w skraplaczach powietrznych?', a: 'Na wykorzystaniu presostat├│w o zr├│┼╝nicowanych nastawach.' },
  { q: 'Gdzie stosuje si─Ö regulacj─Ö obrot├│w wentylator├│w?', a: 'Wsz─Ödzie tam, gdzie wzgl─Ödy ┼Ťrodowiskowe wymuszaj─ů redukcj─Ö ha┼éasu.' },
  { q: 'Na czym polega praca termostatycznego zaworu rozpr─Ö┼╝nego?', a: 'Reguluje wtrysk czynnika do parownika sterowany przegrzaniem.' },
  { q: 'W jakim celu montuje si─Ö zaw├│r zwrotny przed skraplaczem?', a: 'Aby zatrzyma─ç czynnik ciek┼éy i zapobiec migracji do spr─Ö┼╝arki podczas postoju.' },
  { q: 'Czym charakteryzuj─ů si─Ö zawory odcinaj─ůce GBC?', a: 'R─Öczne, dwukierunkowe, do ruroci─ůg├│w cieczowych, ssawnych i gor─ůcego gazu.' },
  { q: 'Czym charakteryzuj─ů si─Ö zawory GVC?', a: 'R─Öczny zaw├│r odcinaj─ůcy z minimalnym spadkiem ci┼Ťnienia.' },
  { q: 'Czym charakteryzuj─ů si─Ö zawory iglicowe?', a: 'Do przemys┼éowych instalacji, wysokich ci┼Ťnie┼ä, szerokiego zakresu temperatur.' },
  { q: 'Na czym polega praca regulatora ci┼Ťnienia parownika KVP?', a: 'Utrzymuje sta┼ée ci┼Ťnienie odparowania i sta┼é─ů temperatur─Ö parownika.' },
  { q: 'W jakim celu stosuje si─Ö wzierniki?', a: 'Do obserwacji stanu czynnika, zawarto┼Ťci wilgoci i przep┼éywu oleju.' },
  { q: 'Gdzie montuje si─Ö regulator ci┼Ťnienia ssania KVL?', a: 'Na przewodzie ssawnym przed spr─Ö┼╝ark─ů, zabezpiecza przed przeci─ů┼╝eniem.' },
  { q: 'Z czego sk┼éada si─Ö linia olejowa?', a: 'Odolejacz, zaw├│r zwrotny, filtr, zawory odcinaj─ůce, zbiornik oleju, zawory poziomu.' },
  { q: 'Do czego s┼éu┼╝y zbiornik czynnika ch┼éodniczego?', a: 'Do gromadzenia zapasu czynnika i wyr├│wnywania zmiennego zapotrzebowania.' },
  { q: 'Jakie jest zastosowanie odolejacza?', a: 'Oddzielanie oleju od czynnika, aby olej wraca┼é do miski olejowej spr─Ö┼╝arki.' },
  { q: 'Co to jest czynnik alternatywny?', a: 'Czynnik o niskim GWP, stosowany w nowych instalacjach.' },
  { q: 'Jakie znasz czynniki alternatywne?', a: 'R744 (CO2), R717 (amoniak), R32, R1234yf, R1234ze, R290 (propan), R600a (izobutan).' },
  { q: 'Co to jest protok├│┼é z Kioto?', a: 'Mi─Ödzynarodowe porozumienie dot. przeciwdzia┼éania globalnemu ociepleniu.' },
  { q: 'Co to jest protok├│┼é Montrealski?', a: 'Dokument w sprawie substancji zuba┼╝aj─ůcych warstw─Ö ozonow─ů (1987 r.).' },
  { q: 'Co to jest czynnik zi─Öbniczy?', a: 'Substancja robocza uczestnicz─ůca w procesach wymiany ciep┼éa w urz─ůdzeniach ch┼éodniczych.' },
  { q: 'Co to jest warstwa ozonowa?', a: 'Warstwa atmosfery o du┼╝ej koncentracji ozonu w stratosferze (12-30 km).' },
  { q: 'Co oznacza skr├│t ODP?', a: 'Ozone Depletion Potential ÔÇô potencja┼é niszczenia warstwy ozonowej.' },
  { q: 'Co to jest GWP?', a: 'Global Warming Potential ÔÇô potencja┼é tworzenia efektu cieplarnianego (wzgl─Ödem CO2).' },
  { q: 'Co to jest efekt cieplarniany?', a: 'Zjawisko podnoszenia si─Ö temperatury przy powierzchni Ziemi wskutek absorpcji promieniowania podczerwonego przez gazy.' },
  { q: 'Co to jest TEWI?', a: 'Total Equivalent Warming Impact ÔÇô ca┼ékowity r├│wnowa┼╝nik efektu cieplarnianego.' },
  { q: 'Jak oblicza si─Ö wska┼║nik TEWI?', a: 'Na podstawie ilo┼Ťci substancji ulatniaj─ůcej si─Ö ├Ś GWP + ┼Ťrednia emisja CO2 z produkcji energii.' },
  { q: 'Co to jest czynnik ekologicznie oboj─Ötny?', a: 'O warto┼Ťciach ODP i GWP = 0 i jak najkr├│tszym czasie ┼╝ycia w atmosferze.' },
  { q: 'Jak dzieli si─Ö syntetyczne czynniki zi─Öbnicze?', a: 'Na jednorodne i mieszaniny (azeotropowe, zeotropowe, bliskoazeotropowe).' },
  { q: 'Na jakie grupy dzielimy czynniki zi─Öbnicze jako zamienniki?', a: 'Drop-in, do retrofitu, do nowych instalacji.' },
  { q: 'Gdzie stosuje si─Ö R1234yf?', a: 'W klimatyzacji samochodowej (GWP<150).' },
  { q: 'Czym charakteryzuje si─Ö R744 (CO2)?', a: 'Naturalny czynnik, niska temp. krytyczna 31,1┬░C, praca w obiegu nadkrytycznym.' },
  { q: 'Czym charakteryzuje si─Ö R717 (amoniak)?', a: 'Zerowy ODP i GWP, wysoka efektywno┼Ť─ç, truj─ůcy.' },
  { q: 'Czym charakteryzuje si─Ö R290 (propan)?', a: 'Naturalny, wydajny, niski GWP, ale ┼éatwopalny (grupa A3).' },
  { q: 'Na czym polega g┼é├│wna pr├│ba szczelno┼Ťci?', a: 'Ci┼Ťnieniowa pr├│ba azotem ÔÇô nie wskazuje miejsca, ale potwierdza szczelno┼Ť─ç.' },
  { q: 'W jakim celu wykonuje si─Ö pr├│┼╝ni─Ö?', a: 'Aby pozby─ç si─Ö wilgoci i usun─ů─ç gazy nieskraplaj─ůce si─Ö.' },
  { q: 'Opisz rodzaje pomp pr├│┼╝niowych.', a: 'Jedno- lub dwustopniowe wyporowe, smarowane olejem.' },
  { q: 'Na czym polega pr├│ba szczelno┼Ťci przez zanurzenie?', a: 'Badany element zanurza si─Ö w k─ůpieli wodnej ÔÇô p─Öcherzyki wskazuj─ů nieszczelno┼Ť─ç.' },
  { q: 'W jakim celu wykonuje si─Ö pr├│┼╝niow─ů pr├│b─Ö szczelno┼Ťci?', a: 'Do usuni─Öcia wody i powietrza z instalacji.' },
  { q: 'Co robi─ç aby zmniejszy─ç ryzyko wycieku?', a: 'Ograniczy─ç d┼éugo┼Ť─ç ruroci─ůg├│w, unika─ç po┼é─ůcze┼ä kielichowych, stosowa─ç lut twardy.' },
  { q: 'Kto mo┼╝e przeprowadzi─ç kontrol─Ö szczelno┼Ťci?', a: 'Personel posiadaj─ůcy certyfikat.' },
  { q: 'Do czego s┼éu┼╝y urz─ůdzenie wykrywaj─ůce gaz?', a: 'Do elektronicznego wykrywania nieszczelno┼Ťci (czu┼éo┼Ť─ç od 2g/rok).' },
  { q: 'Jak dzia┼éa ultrad┼║wi─Ökowy wykrywacz nieszczelno┼Ťci?', a: 'Wykrywa r├│┼╝nic─Ö ci┼Ťnie┼ä, rodzaj gazu nie ma znaczenia.' },
  { q: 'Co to jest karta urz─ůdzenia?', a: 'Dokument dla urz─ůdze┼ä Ôëą3kg F-gaz├│w lub Ôëą5t CO2 eq, z danymi i histori─ů serwisow─ů.' },
  { q: 'Jakie s─ů wymagania dla os├│b prowadz─ůcych odzysk?', a: 'Certyfikat personelu, znajomo┼Ť─ç instrukcji, uprawnienia do nape┼éniania butli.' },
  { q: 'Co oznacza skr├│t F-gaz?', a: 'Fluorowane gazy cieplarniane.' },
  { q: 'Jaki jest cel kontroli szczelno┼Ťci instalacji?', a: 'Wykrycie i ograniczenie wyciek├│w czynnika.' },
  { q: 'Kto odpowiada za dokumentacj─Ö F-gaz w firmie?', a: 'Przedsi─Öbiorca / operator urz─ůdzenia.' },
  { q: 'Ile lat nale┼╝y przechowywa─ç dokumentacj─Ö?', a: 'Minimum 5 lat.' },
  { q: 'Co to jest GWP?', a: 'Wsp├│┼éczynnik wp┼éywu na efekt cieplarniany.' },
  { q: 'Dlaczego R32 wymaga dobrej wentylacji?', a: 'Jest gazem lekko palnym i mo┼╝e wypiera─ç tlen.' },
  { q: 'Co grozi przy podaniu cieczy na ssanie spr─Ö┼╝arki?', a: 'Uszkodzenie spr─Ö┼╝arki (uderzenie hydrauliczne).' },
  { q: 'Jakie s─ů podstawowe ┼Ťrodki ochrony instalatora?', a: 'R─Ökawice, okulary, odzie┼╝ ochronna.' },
  { q: 'Co zrobi─ç przy du┼╝ym wycieku czynnika?', a: 'Zabezpieczy─ç miejsce, przewietrzy─ç, usun─ů─ç ┼║r├│d┼éo zap┼éonu.' },
  { q: 'Czy wolno pracowa─ç bez detektora wyciek├│w?', a: 'Nie ÔÇô detektor jest wymagany przy kontroli.' },
  { q: 'Jak─ů funkcj─Ö pe┼éni spr─Ö┼╝arka?', a: 'Spr─Ö┼╝a i wymusza obieg czynnika.' },
  { q: 'Do czego s┼éu┼╝y parownik?', a: 'Odbiera ciep┼éo z otoczenia (ch┼éodzi).' },
  { q: 'Co robi zaw├│r rozpr─Ö┼╝ny?', a: 'Obni┼╝a ci┼Ťnienie i dawkuje czynnik.' },
  { q: 'Gdzie oddawane jest ciep┼éo w uk┼éadzie ch┼éodniczym?', a: 'W skraplaczu.' },
  { q: 'Co to jest przegrzanie?', a: 'R├│┼╝nica mi─Ödzy temp. parowania a temp. gazu na ssaniu.' },
  { q: 'Jak nale┼╝y nape┼énia─ç R410A?', a: 'W fazie ciek┼éej.' },
  { q: 'Jak kontrolowa─ç ilo┼Ť─ç czynnika?', a: 'Za pomoc─ů wagi.' },
  { q: 'Dlaczego wykonuje si─Ö pr├│┼╝ni─Ö?', a: 'Usuni─Öcie powietrza i wilgoci.' },
  { q: 'Co grozi przy wilgoci w uk┼éadzie?', a: 'Powstawanie kwas├│w i uszkodzenie spr─Ö┼╝arki.' },
  { q: 'Kiedy mo┼╝na poda─ç czynnik gazem?', a: 'Przy ma┼éych korektach ilo┼Ťci czynnika.' },
  { q: 'Do czego s┼éu┼╝y agregat odzyskowy?', a: 'Do odzysku czynnika z instalacji do butli.' },
  { q: 'Jak oznaczy─ç butl─Ö odzyskow─ů?', a: 'Etykiet─ů z nazw─ů czynnika i statusem.' },
  { q: 'Czy wolno miesza─ç czynniki w butli?', a: 'Nie wolno.' },
  { q: 'Co sprawdzamy przed odzyskiem?', a: 'Typ czynnika, stan butli, wag─Ö, ci┼Ťnienie.' },
  { q: 'Jakie s─ů etapy odzysku?', a: 'Najpierw gaz, potem ciecz.' },
  { q: 'Jakie s─ů metody kontroli szczelno┼Ťci?', a: 'Bezpo┼Ťrednia i po┼Ťrednia.' },
  { q: 'Co to jest pr├│ba azotowa?', a: 'Pr├│ba szczelno┼Ťci azotem pod ci┼Ťnieniem.' },
  { q: 'Jak obliczy─ç spadek ci┼Ťnienia?', a: '(Pocz─ůtkowe ÔÇô ko┼äcowe) / pocz─ůtkowe ├Ś 100%.' },
  { q: 'Co oznacza wynik pozytywny pr├│by?', a: 'Brak nieszczelno┼Ťci.' },
  { q: 'Jak cz─Östo wykonuje si─Ö kontrole szczelno┼Ťci?', a: 'Zale┼╝nie od ilo┼Ťci COÔéé eq (np. 1x, 2x, 4x rocznie).' },
  { q: 'Co zawiera karta urz─ůdzenia?', a: 'Dane urz─ůdzenia, ilo┼Ť─ç czynnika, serwisy, kontrole.' },
  { q: 'Kto wpisuje dane do CRO?', a: 'Uprawniony personel / operator.' },
  { q: 'Kiedy nale┼╝y wpisa─ç uzupe┼énienie czynnika?', a: 'Po ka┼╝dej ingerencji w uk┼éad.' },
  { q: 'Czy brak wpisu to wykroczenie?', a: 'Tak.' },
  { q: 'Kto mo┼╝e prowadzi─ç dokumentacj─Ö?', a: 'Certyfikowany personel lub przedsi─Öbiorca.' },
  { q: 'Jak transportowa─ç butle z czynnikiem?', a: 'Zabezpieczone przed przewr├│ceniem i nagrzaniem.' },
  { q: 'Co oznacza butla dwuzaworowa?', a: 'Ma zaw├│r gazowy i cieczowy.' },
  { q: 'Do czego s┼éu┼╝y zaw├│r cieczowy?', a: 'Do poboru cieczy z dna butli.' },
  { q: 'Kiedy u┼╝ywa si─Ö zaworu gazowego?', a: 'Do poboru gazu z g├│rnej cz─Ö┼Ťci.' },
  { q: 'Jak przechowywa─ç butle?', a: 'W wentylowanym miejscu, pionowo, zabezpieczone.' },
  { q: 'Co sprawdzi─ç przed uruchomieniem klimatyzacji?', a: 'Szczelno┼Ť─ç, pr├│┼╝ni─Ö, po┼é─ůczenia, parametry elektryczne.' },
  { q: 'Dlaczego wa┼╝na jest waga czynnika?', a: 'Zbyt du┼╝o lub za ma┼éo = awaria lub spadek wydajno┼Ťci.' },
  { q: 'Co oznacza zbyt wysokie ci┼Ťnienie HP?', a: 'Zabrudzony skraplacz, prze┼éadowanie czynnika.' },
  { q: 'Co oznacza zbyt niskie LP?', a: 'Brak czynnika, zator, z┼éy przep┼éyw powietrza.' },
  { q: 'Jak wykry─ç mikronieszczelno┼Ť─ç?', a: 'Detektor elektroniczny, test azotowy, UV.' },
  { q: 'Kto wydaje certyfikat personalny F-gaz?', a: 'UDT.' },
  { q: 'Jakie s─ů kategorie certyfikat├│w F-gaz?', a: 'I, II, III, IV.' },
  { q: 'Czy firma musi mie─ç certyfikat przedsi─Öbiorcy?', a: 'Tak ÔÇô przy pracy z F-gazami.' },
  { q: 'Kiedy wymagany jest wpis do CRO?', a: 'Przy urz─ůdzeniach obj─Ötych obowi─ůzkiem ewidencji.' },
  { q: 'Jakie kary gro┼╝─ů za brak dokumentacji?', a: 'Kary finansowe / administracyjne.' },
  { q: 'Co oznacza skr├│t CRO?', a: 'Centralny Rejestr Operator├│w.' }
];
