const questionsFGazy = [
  { q: "Jednostką temperatury w układzie SI jest:", a: "K (kelwin)" },
  { q: "W czasie procesu parowania, czynnik chłodniczy:", a: "absorbuje ciepło" },
  { q: "Zawór rozprężny w układzie chłodniczym:", a: "w pewnym zakresie reguluje wartość przegrzania czynnika na wyjściu z parownika" },
  { q: "Wadą węglowodorów jest ich palność, która lokuje te substancje w grupie bezpieczeństwa:", a: "A3" },
  { q: "W raporcie o stanie termostatycznego zaworu rozprężnego:", a: "należy umieścić informacje o strojeniu wartości przegrzewu, jeśli było wykonane" },
  { q: "Sprężarka hermetyczna:", a: "posiada silnik i sprężarkę zamknięte w hermetycznej obudowie" },
  { q: "Skraplacz w układzie chłodniczym:", a: "pośredniczy w odbieraniu ciepła od czynnika chłodniczego w przemianie zwanej skraplaniem" },
  { q: "Zawory odcinające (kulowe lub grzybkowe):", a: "służą do odcinania elementów lub fragmentów układu chłodniczego" },
  { q: "W karcie urządzenia wpisujemy:", a: "zakres przeprowadzonej kontroli szczelności" },
  { q: "Parownik urządzenia chłodniczego może być rozmrażany:", a: "grzałką elektryczną" },
  { q: "Wzrost przegrzewu pary na kolektorze ssawnym sprężarki skutkuje:", a: "wzrostem temperatury końca tłoczenia" },
  { q: "Połączenie lutowane może być miejscem wycieku:", a: "w przypadku pęknięcia lutu na skutek drgań" },
  { q: "Czujniki temperatury na rurociągu chłodniczym mogą być montowane w sposób:", a: "przylgowy lub kieszeniowy" },
  { q: "Określenie ODP dotyczy:", a: "substancji zubażających warstwę ozonową" },
  { q: "Pojemnik służący do przechowywania F-gazów musi posiadać etykietę z min. informacjami:", a: "typ i rodzaj F-gazu" },
  { q: "Specyfikacja fluorowanych gazów cieplarnianych:", a: "znajduje się w załączniku do rozporządzenia UE (WE) nr 517/2014" },
  { q: "Stosowanie układów nadkrytycznych:", a: "jest mniej korzystne pod względem efektywności energetycznej" },
  { q: "Karta urządzenia zawiera m.in.:", a: "ilość odzyskanego fluorowanego gazu cieplarnianego" },
  { q: "W karcie urządzenia wpisujemy:", a: "ilość, rodzaj i GWP czynnika chłodniczego umieszczonego w urządzeniu" },
  { q: "Wydajność skraplacza powietrznego można regulować:", a: "np. poprzez załączenie lub wyłączanie wentylatorów" },
  { q: "Czynnik R-744/CO2 charakteryzuje się:", a: "niską temperaturą krytyczną (ok 30°C) w związku z tym pracą w trybie pod i nadkrytycznym" },
  { q: "W lamelowym parowniku powietrznym rozdział czynnika odbywa się poprzez:", a: "rozdzielacz czynnika" },
  { q: "Podmiot który wwozi F-gazy na terytorium RP ma obowiązek złożyć:", a: "sprawozdanie do Urzędu Skarbowego właściwego dla miejsca rejestracji podmiotu" },
  { q: "Montowanie stałego układu wykrywania wycieków:", a: "pozwala zmniejszyć ilość wycieków" },
  { q: "W karcie urządzenia wpisujemy:", a: "ilość i rodzaj oleju zanieczyszczonego F-gazem który został odzyskany z instalacji" },
  { q: "W raporcie o stanie sprężarki:", a: "należy umieścić informacje o poborze prądu w ustalonym stanie pracy sprężarki" },
  { q: "W raporcie o stanie skraplacza powietrznego:", a: "należy umieścić informacje o przeprowadzonym czyszczeniu bloku lamelowego" },
  { q: "W raporcie o stanie lamelowego parownika powietrznego:", a: "należy umieścić informację o usuwaniu nadmiaru lodu" },
  { q: "Jednym z alternatywnych czynników (R600A) jest:", a: "izobutan" },
  { q: "Redukowanie mocy chłodniczej urządzeń:", a: "skutkuje zmniejszeniem napełnienia i jest metodą zmniejszenia stosowania F-gazów" },
  { q: "Jednostką masy w układzie SI jest:", a: "kg" },
  { q: "Wskaźnik wilgoci w układzie:", a: "wskazuje obecność wilgoci i konieczność wymiany filtra odwadniacza" },
  { q: "Separator cieczy:", a: "pozwala zapobiec zasysaniu kropel cieczy przez sprężarkę" },
  { q: "Sprawozdania z art. 39 ustawy z dnia 15 maja 2015:", a: "są przekazywane w postaci formularzy elektronicznych" },
  { q: "Państwa członkowskie, które ratyfikowały protokół z Kioto:", a: "zobowiązały się do redukcji emisji gazów cieplarnianych" },
  { q: "Określenie F-gaz odnosi się do:", a: "wodorofluorowęglowodorów (HFC), perfluorowęglowodorów (PFC) i heksafluorku siarki SF6" },
  { q: "W czasie pracy układu, w sprężarce chłodniczej, para czynnika:", a: "podgrzewa się" },
  { q: "Karta urządzenia zawiera min.:", a: "dane operatora urządzenia" },
  { q: "Skręcone połączenie rurociągu może być miejscem wycieku w przypadku:", a: "poluzowania się nakrętki na gwincie" },
  { q: "Metodą zmniejszenia emisji F-gazów jest:", a: "zwiększenie częstotliwości kontroli szczelności" },
  { q: "W zanieczyszczonym skraplaczu powietrznym:", a: "spada współczynnik przewodzenia ciepła" },
  { q: "Jednostką ciśnienia w układzie SI jest:", a: "Pa (paskal)" },
  { q: "Sprężarka w układzie chłodniczym:", a: "spręża czynnik chłodniczy" },
  { q: "Parownik w układzie chłodniczym:", a: "pośredniczy w absorbowaniu ciepła przez czynnik chłodniczy w przemianie zwanej parowaniem" },
  { q: "Regulator ciśnienia skraplania:", a: "utrzymuje ciśnienie skraplania na zadanym poziomie" },
  { q: "Zbiornik cieczy w układzie chłodniczym służy do:", a: "kompensacji zmiennej ilości cyrkulującego czynnika w układzie" },
  { q: "Efekt cieplarniany to zjawisko polegające na:", a: "podnoszeniu się średniej temperatury atmosfery ziemskiej" },
  { q: "Protokół z ciśnieniowej próby szczelności zawiera m.in.:", a: "początkowe oraz końcowe ciśnienia i temperatury próby" },
  { q: "Urządzenie zawierające F-gaz musi posiadać etykietę z:", a: "wartością napełnienia w kg i ekwiwalentem CO2" },
  { q: "Podmioty objęte obowiązkiem z art. 39 ustawy:", a: "powinny zarejestrować się w Bazie Danych Sprawozdań (BDS)" },
  { q: "Termostatyczny zawór rozprężny:", a: "dozuje czynnik chłodniczy do parownika aby utrzymać zadane przegrzanie" },
  { q: "Skraplacze ze względu na medium można podzielić:", a: "m.in. na powietrzne i wodne" },
  { q: "Chcąc zastosować odtajanie parownika powietrzem obiegowym:", a: "temperatura powietrza musi być wyższa od temperatury topnienia lodu" },
  { q: "Presostaty ciśnieniowe w układzie chłodniczym:", a: "mają za zadanie wyłączenie sprężarki gdy przekraczane są ciśnienia dopuszczalne" },
  { q: "Zawory odcinające zbiornik cieczy:", a: "powinny być montowane jak najbliżej króćców wlotowych i wylotowych zbiornika" },
  { q: "Zbiornik cieczy pozwala na:", a: "magazynowanie całości lub części czynnika w czasie postojów lub remontów" },
  { q: "Separator oleju:", a: "wychwytuje olej emitowany przez sprężarkę" },
  { q: "Separator oleju może działać na zasadzie:", a: "zbiornika w którym mieszanina pary i oleju uzyskuje ruch wirowy" },
  { q: "Zbiornik oleju w układzie chłodniczym:", a: "odpowiada za zapewnienie dostatecznej ilości oleju do smarowania sprężarek" },
  { q: "Regulator poziomu oleju w sprężarce odpowiada za:", a: "utrzymanie odpowiedniego poziomu oleju w sprężarce" },
  { q: "Proces rozmrażania może być zakończony:", a: "po upływie zadanego czasu trwania tego procesu" },
  { q: "Proces rozmrażania może być zakończony:", a: "po osiągnięciu zadanej końcowej temperatury" },
  { q: "Który z międzynarodowych aktów prawnych dotyczy substancji zubożających warstwę ozonową", a: "Protokół montrealski w sprawie substancji zubożających warstwę ozonową." },
  { q: "Który z międzynarodowych aktów prawnych dotyczy zmian klimatu", a: "Protokół z Kioto do Ramowej konwencji Narodów Zjednoczonych w sprawie zmian klimatu." },
  { q: "Najważniejszym polskim aktem prawnym dotyczącym SZWO oraz F-gazów jest:", a: "Ustawa z dn. 15.05.2015 r. o substancjach zubożających warstwę ozonową oraz o niektórych fluorowanych gazach cieplarnianych (Dz.U. 2015 poz. 881 z późn. zm.)." },
  { q: "Zakaz stosowania jakich czynników obowiązuje od 1 stycznia 2020 r.", a: "Nie wolno stosować nowych czynników o GWP powyżej 2500 do serwisowania urządzeń o napełnieniu 40t ekwiwalentu CO2 lub większej." },
  { q: "Co oznacza skrót HFC", a: "Hydrofluorowęglowodór – czynnik chłodniczy nie przyczyniający się do niszczenia ozonu, ale wpływający na efekt cieplarniany." },
  { q: "Co oznacza skrót SZWO", a: "Substancje zubożające warstwę ozonową – pochodne węglowodorów zawierające chlor lub brom." },
  { q: "Co to są substancje kontrolowane", a: "Substancje wymienione w załączniku I rozporządzenia (WE) NR 1005/2009." },
  { q: "Co to są F-gazy", a: "Fluorowane gazy cieplarniane: HFC, PFC, SF6 i inne gazy zawierające fluor." },
  { q: "Jakie minimalne wyposażenie powinno mieć certyfikowane przedsiębiorstwo", a: "Zgodne z Rozporządzeniem Ministra Rozwoju i Finansów z dnia 7 grudnia 2017 r. (Dz.U. 2017 poz. 2417)." },
  { q: "Kiedy przepisy nakładają obowiązek założenia Karty Urządzenia", a: "Dla urządzeń zawierających 3 kg lub więcej F-gazów/SZWO lub co najmniej 5 ton ekwiwalentu CO2." },
  { q: "Czyim obowiązkiem jest założenie Karty Urządzenia", a: "Obowiązek operatora urządzenia." },
  { q: "Kto może dokonywać wpisów w Karcie Urządzenia", a: "Osoby posiadające certyfikat dla personelu." },
  { q: "W jakim terminie sporządza się Kartę Urządzenia", a: "W ciągu 15 dni od dostarczenia urządzenia lub zakończenia instalacji." },
  { q: "Od czego zależy częstotliwość kontroli szczelności", a: "Od ilości ekwiwalentu CO2: 5-50t CO2 eq – co 12/24 mies.; 50-500t – co 6/12 mies.; powyżej 500t – co 3/6 mies." },
  { q: "Jakimi metodami można dokonać pomiaru szczelności", a: "Metodą pośrednią lub bezpośrednią." },
  { q: "Na czym polega metoda pośrednia", a: "Kontrola wzrokowa i ręczna oraz analiza ciśnienia, temperatury, prądu, poziomów płynów." },
  { q: "Na czym polega metoda bezpośrednia", a: "Użycie urządzenia wykrywającego gaz, płynu detekcyjnego, barwnika, mydlin." },
  { q: "Kogo dotyczy Certyfikat dla personelu", a: "Osób wykonujących: kontrolę szczelności, odzysk, instalację, naprawę, konserwację, serwisowanie, likwidację." },
  { q: "Jakie wymagania musi spełniać osoba starająca się o Certyfikat personelu", a: "Pełnoletnia, niekarana za przestępstwa przeciwko środowisku, po zdanym egzaminie." },
  { q: "Kiedy należy uzyskać Certyfikat dla przedsiębiorstwa", a: "Przy instalacji, naprawie, konserwacji, serwisowaniu lub likwidacji urządzeń F-gaz." },
  { q: "Jakie procedury musi posiadać przedsiębiorstwo", a: "Procedurę instalacji, likwidacji, odzysku oraz konserwacji, naprawy lub serwisowania." },
  { q: "Jaki zakaz dot. SZWO obowiązuje od 01.01.2015", a: "Całkowity zakaz serwisowania urządzeń zawierających SZWO." },
  { q: "Jakim kodem odpadu oznakowuje się CFC, HCFC, HFC", a: "14 06 01*" },
  { q: "Co to jest temperatura", a: "Miara energii cząstek ciała wywołanej dopływem ciepła." },
  { q: "0°C to ile Kelwinów", a: "273,15 K" },
  { q: "Co to jest ciśnienie", a: "Siła naporu działająca prostopadle do powierzchni, oznaczana p [Pa]." },
  { q: "Paskal [Pa] to:", a: "stosunek siły 1 N do powierzchni 1 m²." },
  { q: "Co to jest masa", a: "Właściwość materii określająca opór przy zmianie ruchu." },
  { q: "Co to jest gęstość", a: "Masa jednostki objętości ciała." },
  { q: "Z jakich elementów składa się podstawowe urządzenie ziębiące", a: "Sprężarka, skraplacz, parownik, zawór rozprężny." },
  { q: "Co to jest entalpia", a: "Wielkość fizyczna będąca sumą energii wewnętrznej i iloczynu pV." },
  { q: "Jak klasyfikujemy substancje w urządzeniach chłodniczych", a: "Syntetyczne (jednorodne, mieszaniny) i naturalne (organiczne, nieorganiczne)." },
  { q: "Co to są mieszaniny zeotropowe", a: "Mieszaniny o różnej lotności, wykazują poślizg temperaturowy." },
  { q: "Co to są mieszaniny azeotropowe", a: "Mieszaniny w równowadze termodynamicznej – skład pary i cieczy taki sam." },
  { q: "Jak dzielimy sprężarki", a: "Na przepływowe i wyporowe; wyporowe na tłokowe i rotacyjne." },
  { q: "Co to jest stopień sprężania", a: "Iloraz końcowego ciśnienia sprężarki do ciśnienia ssania." },
  { q: "Jak działa sprężarka hermetyczna tłokowa", a: "Obudowa spawana, silnik i sprężarka na wspólnym wale, chłodzona zasysanym czynnikiem." },
  { q: "Jak działa sprężarka półhermetyczna", a: "Łączy cechy otwartej i hermetycznej – możliwość remontów, smarowanie ciśnieniowe." },
  { q: "Jak działa sprężarka spiralna", a: "Dwie spirale nad silnikiem, gaz chłodzi silnik i jest sprężany między spiralami." },
  { q: "Jak dzieli się parowniki", a: "Do chłodzenia cieczy, powietrza (chłodnice) i ciał stałych." },
  { q: "Wymień metody odszraniania parownika:", a: "naturalne, elektryczne, gorącymi parami czynnika." },
  { q: "Omów zasadę działania skraplacza:", a: "Odprowadza ciepło pobrane w parowniku + ciepło sprężania, para skrapla się oddając ciepło." },
  { q: "Wymień rodzaje skraplaczy:", a: "powietrzne, wodne, wyparne, płytowe, współosiowe." },
  { q: "Czym charakteryzuje się skraplacz natryskowo-wyparny", a: "Chłodzony powietrzem i wodą natryskiwaną przeciwprądowo." },
  { q: "Na czym polega regulacja ciśnienia w skraplaczach powietrznych", a: "Na wykorzystaniu presostatów o zróżnicowanych nastawach." },
  { q: "Gdzie stosuje się regulację obrotów wentylatorów", a: "Wszędzie tam, gdzie względy środowiskowe wymuszają redukcję hałasu." },
  { q: "Na czym polega praca termostatycznego zaworu rozprężnego", a: "Reguluje wtrysk czynnika do parownika sterowany przegrzaniem." },
  { q: "W jakim celu montuje się zawór zwrotny przed skraplaczem", a: "Aby zatrzymać czynnik ciekły i zapobiec migracji do sprężarki podczas postoju." },
  { q: "Czym charakteryzują się zawory odcinające GBC", a: "Ręczne, dwukierunkowe, do rurociągów cieczowych, ssawnych i gorącego gazu." },
  { q: "Czym charakteryzują się zawory GVC", a: "Ręczny zawór odcinający z minimalnym spadkiem ciśnienia." },
  { q: "Czym charakteryzują się zawory iglicowe", a: "Do przemysłowych instalacji, wysokich ciśnień, szerokiego zakresu temperatur." },
  { q: "Na czym polega praca regulatora ciśnienia parownika KVP", a: "Utrzymuje stałe ciśnienie odparowania i stałą temperaturę parownika." },
  { q: "W jakim celu stosuje się wzierniki", a: "Do obserwacji stanu czynnika, zawartości wilgoci i przepływu oleju." },
  { q: "Gdzie montuje się regulator ciśnienia ssania KVL", a: "Na przewodzie ssawnym przed sprężarką, zabezpiecza przed przeciążeniem." },
  { q: "Z czego składa się linia olejowa", a: "Odolejacz, zawór zwrotny, filtr, zawory odcinające, zbiornik oleju, zawory poziomu." },
  { q: "Do czego służy zbiornik czynnika chłodniczego", a: "Do gromadzenia zapasu czynnika i wyrównywania zmiennego zapotrzebowania." },
  { q: "Jakie jest zastosowanie odolejacza", a: "Oddzielanie oleju od czynnika, aby olej wracał do miski olejowej sprężarki." },
  { q: "Co to jest czynnik alternatywny", a: "Czynnik o niskim GWP, stosowany w nowych instalacjach." },
  { q: "Jakie znasz czynniki alternatywne", a: "R744 (CO2), R717 (amoniak), R32, R1234yf, R1234ze, R290 (propan), R600a (izobutan)." },
  { q: "Co to jest protokół z Kioto", a: "Międzynarodowe porozumienie dot. przeciwdziałania globalnemu ociepleniu." },
  { q: "Co to jest protokół Montrealski", a: "Dokument w sprawie substancji zubażających warstwę ozonową (1987 r.)." },
  { q: "Co to jest czynnik ziębniczy", a: "Substancja robocza uczestnicząca w procesach wymiany ciepła w urządzeniach chłodniczych." },
  { q: "Co to jest warstwa ozonowa", a: "Warstwa atmosfery o dużej koncentracji ozonu w stratosferze (12-30 km)." },
  { q: "Co oznacza skrót ODP", a: "Ozone Depletion Potential – potencjał niszczenia warstwy ozonowej." },
  { q: "Co to jest GWP", a: "Global Warming Potential – potencjał tworzenia efektu cieplarnianego (względem CO2)." },
  { q: "Co to jest efekt cieplarniany", a: "Zjawisko podnoszenia się temperatury przy powierzchni Ziemi wskutek absorpcji promieniowania podczerwonego przez gazy." },
  { q: "Co to jest TEWI", a: "Total Equivalent Warming Impact – całkowity równoważnik efektu cieplarnianego." },
  { q: "Jak oblicza się wskaźnik TEWI", a: "Na podstawie ilości substancji ulatniającej się × GWP + średnia emisja CO2 z produkcji energii." },
  { q: "Co to jest czynnik ekologicznie obojętny", a: "O wartościach ODP i GWP = 0 i jak najkrótszym czasie życia w atmosferze." },
  { q: "Jak dzieli się syntetyczne czynniki ziębnicze", a: "Na jednorodne i mieszaniny (azeotropowe, zeotropowe, bliskoazeotropowe)." },
  { q: "Na jakie grupy dzielimy czynniki ziębnicze jako zamienniki", a: "Drop-in, do retrofitu, do nowych instalacji." },
  { q: "Gdzie stosuje się R1234yf", a: "W klimatyzacji samochodowej (GWP<150)." },
  { q: "Czym charakteryzuje się R744 (CO2)", a: "Naturalny czynnik, niska temp. krytyczna 31,1°C, praca w obiegu nadkrytycznym." },
  { q: "Czym charakteryzuje się R717 (amoniak)", a: "Zerowy ODP i GWP, wysoka efektywność, trujący." },
  { q: "Czym charakteryzuje się R290 (propan)", a: "Naturalny, wydajny, niski GWP, ale łatwopalny (grupa A3)." },
  { q: "Na czym polega główna próba szczelności", a: "Ciśnieniowa próba azotem – nie wskazuje miejsca, ale potwierdza szczelność." },
  { q: "W jakim celu wykonuje się próżnię", a: "Aby pozbyć się wilgoci i usunąć gazy nieskraplające się." },
  { q: "Opisz rodzaje pomp próżniowych.", a: "Jedno- lub dwustopniowe wyporowe, smarowane olejem." },
  { q: "Na czym polega próba szczelności przez zanurzenie", a: "Badany element zanurza się w kąpieli wodnej – pęcherzyki wskazują nieszczelność." },
  { q: "W jakim celu wykonuje się próżniową próbę szczelności", a: "Do usunięcia wody i powietrza z instalacji." },
  { q: "Co robić aby zmniejszyć ryzyko wycieku", a: "Ograniczyć długość rurociągów, unikać połączeń kielichowych, stosować lut twardy." },
  { q: "Kto może przeprowadzić kontrolę szczelności", a: "Personel posiadający certyfikat." },
  { q: "Do czego służy urządzenie wykrywające gaz", a: "Do elektronicznego wykrywania nieszczelności (czułość od 2g/rok)." },
  { q: "Jak działa ultradźwiękowy wykrywacz nieszczelności", a: "Wykrywa różnicę ciśnień, rodzaj gazu nie ma znaczenia." },
  { q: "Co to jest karta urządzenia", a: "Dokument dla urządzeń ≥3kg F-gazów lub ≥5t CO2 eq, z danymi i historią serwisową." },
  { q: "Jakie są wymagania dla osób prowadzących odzysk", a: "Certyfikat personelu, znajomość instrukcji, uprawnienia do napełniania butli." },
  { q: "Co oznacza skrót F-gaz", a: "Fluorowane gazy cieplarniane." },
  { q: "Jaki jest cel kontroli szczelności instalacji", a: "Wykrycie i ograniczenie wycieków czynnika." },
  { q: "Kto odpowiada za dokumentację F-gaz w firmie", a: "Przedsiębiorca / operator urządzenia." },
  { q: "Ile lat należy przechowywać dokumentację", a: "Minimum 5 lat." },
  { q: "Co to jest GWP", a: "Współczynnik wpływu na efekt cieplarniany." },
  { q: "Dlaczego R32 wymaga dobrej wentylacji", a: "Jest gazem lekko palnym i może wypierać tlen." },
  { q: "Co grozi przy podaniu cieczy na ssanie sprężarki", a: "Uszkodzenie sprężarki (uderzenie hydrauliczne)." },
  { q: "Jakie są podstawowe środki ochrony instalatora", a: "Rękawice, okulary, odzież ochronna." },
  { q: "Co zrobić przy dużym wycieku czynnika", a: "Zabezpieczyć miejsce, przewietrzyć, usunąć źródło zapłonu." },
  { q: "Czy wolno pracować bez detektora wycieków", a: "Nie – detektor jest wymagany przy kontroli." },
  { q: "Jaką funkcję pełni sprężarka", a: "Spręża i wymusza obieg czynnika." },
  { q: "Do czego służy parownik", a: "Odbiera ciepło z otoczenia (chłodzi)." },
  { q: "Co robi zawór rozprężny", a: "Obniża ciśnienie i dawkuje czynnik." },
  { q: "Gdzie oddawane jest ciepło w układzie chłodniczym", a: "W skraplaczu." },
  { q: "Co to jest przegrzanie", a: "Różnica między temp. parowania a temp. gazu na ssaniu." },
  { q: "Jak należy napełniać R410A", a: "W fazie ciekłej." },
  { q: "Jak kontrolować ilość czynnika", a: "Za pomocą wagi." },
  { q: "Dlaczego wykonuje się próżnię", a: "Usunięcie powietrza i wilgoci." },
  { q: "Co grozi przy wilgoci w układzie", a: "Powstawanie kwasów i uszkodzenie sprężarki." },
  { q: "Kiedy można podać czynnik gazem", a: "Przy małych korektach ilości czynnika." },
  { q: "Do czego służy agregat odzyskowy", a: "Do odzysku czynnika z instalacji do butli." },
  { q: "Jak oznaczyć butlę odzyskową", a: "Etykietą z nazwą czynnika i statusem." },
  { q: "Czy wolno mieszać czynniki w butli", a: "Nie wolno." },
  { q: "Co sprawdzamy przed odzyskiem", a: "Typ czynnika, stan butli, wagę, ciśnienie." },
  { q: "Jakie są etapy odzysku", a: "Najpierw gaz, potem ciecz." },
  { q: "Jakie są metody kontroli szczelności", a: "Bezpośrednia i pośrednia." },
  { q: "Co to jest próba azotowa", a: "Próba szczelności azotem pod ciśnieniem." },
  { q: "Jak obliczyć spadek ciśnienia", a: "(Początkowe – końcowe) / początkowe × 100%." },
  { q: "Co oznacza wynik pozytywny próby", a: "Brak nieszczelności." },
  { q: "Jak często wykonuje się kontrole szczelności", a: "Zależnie od ilości CO₂ eq (np. 1x, 2x, 4x rocznie)." },
  { q: "Co zawiera karta urządzenia", a: "Dane urządzenia, ilość czynnika, serwisy, kontrole." },
  { q: "Kto wpisuje dane do CRO", a: "Uprawniony personel / operator." },
  { q: "Kiedy należy wpisać uzupełnienie czynnika", a: "Po każdej ingerencji w układ." },
  { q: "Czy brak wpisu to wykroczenie", a: "Tak." },
  { q: "Kto może prowadzić dokumentację", a: "Certyfikowany personel lub przedsiębiorca." },
  { q: "Jak transportować butle z czynnikiem", a: "Zabezpieczone przed przewróceniem i nagrzaniem." },
  { q: "Co oznacza butla dwuzaworowa", a: "Ma zawór gazowy i cieczowy." },
  { q: "Do czego służy zawór cieczowy", a: "Do poboru cieczy z dna butli." },
  { q: "Kiedy używa się zaworu gazowego", a: "Do poboru gazu z górnej części." },
  { q: "Jak przechowywać butle", a: "W wentylowanym miejscu, pionowo, zabezpieczone." },
  { q: "Co sprawdzić przed uruchomieniem klimatyzacji", a: "Szczelność, próżnię, połączenia, parametry elektryczne." },
  { q: "Dlaczego ważna jest waga czynnika", a: "Zbyt dużo lub za mało = awaria lub spadek wydajności." },
  { q: "Co oznacza zbyt wysokie ciśnienie HP", a: "Zabrudzony skraplacz, przeładowanie czynnika." },
  { q: "Co oznacza zbyt niskie LP", a: "Brak czynnika, zator, zły przepływ powietrza." },
  { q: "Jak wykryć mikronieszczelność", a: "Detektor elektroniczny, test azotowy, UV." },
  { q: "Kto wydaje certyfikat personalny F-gaz", a: "UDT." },
  { q: "Jakie są kategorie certyfikatów F-gaz", a: "I, II, III, IV." },
  { q: "Czy firma musi mieć certyfikat przedsiębiorcy", a: "Tak – przy pracy z F-gazami." },
  { q: "Kiedy wymagany jest wpis do CRO", a: "Przy urządzeniach objętych obowiązkiem ewidencji." },
  { q: "Jakie kary grożą za brak dokumentacji", a: "Kary finansowe / administracyjne." },
  { q: "Co oznacza skrót CRO", a: "Centralny Rejestr Operatorów." },
  { q: "W raporcie o stanie sprężarki:", a: "należy min. umieścić informacje o przeprowadzonej wymianie oleju, jeśli takowa miała miejsce" },
  { q: "Zawór rozprężny w układzie chłodniczym:", a: "odpowiada za zasilanie parownika w odpowiednią ilością czynnika" },
  { q: "W raporcie o stanie skraplacza powietrznego:", a: "należy umieścić informacje o stanie lamel" },
  { q: "Połączenie lutowane rurowe może być miejscem wycieku:", a: "w przypadku pęknięcia lutu na skutek cyklicznych, znacznych zmian temperatury" },
  { q: "W karcie urządzenia wpisujemy:", a: "nazwisko i imię oraz numer uprawnień osoby dokonującej czynności serwisowych" },
];
